### PR TITLE
[blocked] application: rework the installation form generation

### PR DESCRIPTION
**Pull request by virtualtam**
Relates to #372

Modifications:
 - HTML template
   - use a form fieldset layout + minimal CSS
   - do not include Shaarli headers & footers

TODO:
 - HTML template
   - generate a timezone fieldset
 - ApplicationUtils
   - assimilate the `install()` function
   - apply coding conventions
   - add test coverage when possible/relevant

[EDIT] Blocked by:
- [ ] #397 - move the `PageBuilder` class to a proper file
- [ ] timezone: defer HTML/form generation to HTML templates

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Good idea! Why did you create a separate CSS file?

Also, if you touch `ApplicationUtils`, can you add the `@throw` on `checkUpdate()`?

**Comment by virtualtam** [comment]
The separate CSS has (at least for now / early testing) several advantages:
- keep things as simple as possible in the install page
- avoid inheriting from the main CSS (lots of side-effects)

**Comment by virtualtam** [comment]
`@throw` added in #398

**Comment by virtualtam** [comment]
Closing for now, the form/fieldset may be reused for #266

**Pull request closed without merging**
