### PR TITLE
github actions: build OCI images that contain both amd64 and armv7

### PR DESCRIPTION
**Pull request by nodiscc**
- ref. https://docs.docker.com/engine/reference/commandline/buildx_build/#platform
- ref. https://docs.docker.com/build/ci/github-actions/multi-platform/
- replaces https://github.com/shaarli/Shaarli/pull/1496
- make docker image name configurable through CI variables for easier testing

### CODE REVIEW

**Comment by nodiscc** [comment]
Rebased, PR description updated. Verified that the resulting image contains both `amd64` and `arm/v7` builds:

```
$ docker buildx imagetools inspect ghcr.io/nodiscc/shaarli:latest
Name:      ghcr.io/nodiscc/shaarli:latest
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:c7233e7e11f20c37709150255f66dcb7aa23757a4df7eb258feae9c1c87a42aa
           
Manifests: 
  Name:      ghcr.io/nodiscc/shaarli:latest@sha256:c4c74907f18c35b50d30b22e3219c0b8aaee5cb0e943162fedf9c7133713c7aa
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64
             
  Name:      ghcr.io/nodiscc/shaarli:latest@sha256:2f68dde7e685ca41250cafb7a3d084aeea80f057e28710507b18ed61015a5da2
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm/v7
```

I made the image name configurable through Github Actions CI variables/secrets, so I will now set `DOCKER_IMAGE = shaarli/shaarli` in https://github.com/shaarli/Shaarli/settings/secrets/actions.

I will now close https://github.com/shaarli/Shaarli/pull/1496 since this PR replaces it. I have no way to test if the resulting image actually works (currently no ARM machine to run it, I will try to create an ARMv7 VM with libvirt/qemu but this might take some time). Maybe @cerebrate or other users with an ARM machine would be able to test `ghcr.io/shaarli/shaarli:latest` once this PR is merged?

**Comment by cerebrate** [comment]
Happy to do that testing.

...incidentally, since it's got a lot more popular since I was first noodling about with arm devices, maybe it's time to add arm64 to the build matrix also?

**Comment by ArthurHoaro** [comment]
> I made the image name configurable through Github Actions CI variables/secrets, so I will now set DOCKER_IMAGE = shaarli/shaarli in shaarli/Shaarli/settings/secrets/actions.

Wouldn't it make sense to use a variable instead of a secret, since it's not sensitive information?

> ...incidentally, since it's got a lot more popular since I was first noodling about with arm devices, maybe it's time to add arm64 to the build matrix also?

Agreed, and I happen to have a brand new arm64 chip to test it!

Current behavior:

```
> docker pull ghcr.io/shaarli/shaarli
Using default tag: latest
latest: Pulling from shaarli/shaarli
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by cerebrate** [comment]
@nodiscc Looks to be running fine on my 32-bit ARM machine (Raspberry Pi).

**Comment by nodiscc** [comment]
> Wouldn't it make sense to use a variable instead of a secret, since it's not sensitive information?

A plain variable would be more appropriate, but I used secrets since we already use them - this way the syntax stays consistent (https://docs.github.com/en/actions/learn-github-actions/variables vs https://docs.github.com/en/actions/security-guides/encrypted-secrets), and everything is immediately visible on [Secrets and variables > Actions](https://github.com/shaarli/Shaarli/settings/secrets/actions) - I prefer consistency to correctness :) But feel free to change it.

**Review by Teresayluis — APPROVED** [review]

**Review by Teresayluis — CHANGES_REQUESTED** [review]
- [ ]

**Pull request merged**
