### PR TITLE
fixes "adding a link should return added link's hash"

### PR DESCRIPTION
**Pull request by mro**
a.k.a. #356, partially reverts 775803a0

### CODE REVIEW

**Comment by mro** [comment]
@nodiscc may I ask you personally about your opinion concerning this pull request?

**Comment by dimtion** [comment]
I'd like to second @mro on this pull request. For now it *hard* for a third party client to know for sure if a link has successfully been posted.

**Comment by nodiscc** [comment]
I have nothing against this patch if it doesn't introduce any undesired side effects.

From memory, the problem was that, after deleting a link, you would be redirected to an anchor pointing to the link (that you just deleted). All redirects should be tested. Also I haven't dug into Shaarli's source code for a while, so please excuse the approximative answer.

**Comment by ArthurHoaro** [comment]
By removing `generateLocation`, you're probably introducing a regression (see #256).

I'll try to give a look at this soon.

**Comment by mro** [comment]
without being 100% sure, the regression of #256 would come as a surprise to me however, because #256 was about adding a tag - here it's about adding a link. So it's IMO a different use case that was isolated prior the introduction of `generateLocation` in 775803a.

If interested I may try adding a test over at https://github.com/mro/Shaarli-API-test if you can describe the conditions to me.

**Comment by ArthurHoaro** [comment]
Can't test it now but at least one probable broken use case:

  * set `network.http.referer.spoofSource` to `true`.
  * login to shaarli.
  * go one page 2 or filter by tag.
  * edit a link and save.

Expected behavior: go to homepage.

Probable behavior here: redirection loop or stay on the same page.

**Comment by ArthurHoaro** [comment]
Suggestion in `generateLocation()`:

replace
```
$final_referer = '?';
```
by
```
$final_referer = '?' . parse_url($referer, PHP_URL_FRAGMENT);
```

It's probably not the most elegant way, but I think it would work and won't cause any harm.

**Comment by mro** [comment]
Hi @ArthurHoaro are there any *actual* broken use cases that prevent a merge?

**Comment by ArthurHoaro** [comment]
The use case I provided is broken. I'm submitting a PR which fixes my regression without removing what's fixed in 775803a05cdba9d7fc1b37af4b15ecd80a8cbcc2.

**Pull request closed without merging**
