### PR TITLE
Add URL cleaning filters + refactoring

### PR DESCRIPTION
**Pull request by nodiscc**
* Add some filters to clean URLs 	
 * cleanup: refactor annoying URL patterns in a single loop

### CODE REVIEW

**Comment by nodiscc** [comment]
Note that we may want to do things differently before merging: We have to add **2 rules** for each "dirty" parameter depending on it's position in the URL (eg `&utm_source=` and `?utm_source=`)

@mro your regex-fu would be appreciated

**Comment by mro** [comment]
@nodiscc  https://github.com/shaarli/Shaarli/pull/141#issuecomment-77224137: can you give me test cases as to what to strip and what to keep? Then I'll build some regexps.

**Comment by pikzen** [comment]
>Note that we may want to do things differently before merging: We have to add 2 rules for each "dirty" parameter depending on it's position in the URL (eg &utm_source= and ?utm_source=)

It depends if we're going the full regex way (with `preg_match` to match each parameter) or just staying with plaintext comparison.Strpos comparison requires both the ? and & version, regexes would be `/[\?&]utm_whatever/`

**Comment by mro** [comment]
@pikzen `preg_replace`. pattern `/[\?&]utm_whatever=[^&]*/` => `""`

**Comment by mro** [comment]
// Remove annoying parameters added by FeedBurner, GoogleFeedProxy, Facebook...
        $annoyingpatterns = array(
          '/[\?&]utm_source=[^&]*/',    // google analytics
          '/[\?&]utm_campaign=[^&]*/',  // google analytics
          '/[\?&]utm_medium=[^&]*/',    // google analytics
          '/#xtor=RSS-[^&]*/',          // who?
          '/[\?&]fb_[^&]*/',            // facebook? eats all parameters with name starting with fb_
          '/[\?&]__scoop[^&]*/',        // who? eats all parameters with name starting with __scoop
          '/#tk\.rss_all\?/',           // who? eats the trailing question mark in case
        );
        foreach($annoyingpatterns as $pattern)
            $url = preg_replace($pattern, "", $url);

**Comment by nodiscc** [comment]
@mro Great, I think your solution also solves https://github.com/shaarli/Shaarli/issues/136 ? (just remove the relevant param, not everything after)

<sub>I've investigated the different uses of these parameters, `fb_` is for facebook campaigns, `#xtor` seems to be a general tracking/campaign tool, I don't know for the others. Maybe it's not necessary to detail the origin - I'd just put everything on one line</sub>

**Comment by nodiscc** [comment]
Tested and working, I also added more URL parameters in https://github.com/nodiscc/Shaarli/commit/baf5cbf27d18467d838a24b6f451036cebaa27bf

Thanks @mro @alexisju. Merging.

**Comment by mro** [comment]
@nodiscc https://github.com/shaarli/Shaarli/pull/141#issuecomment-77338834: yes, it solves #136.

**Comment by nicolasdanelon** [comment]
hi, today I save this link http://dangerousminds.net/comments/a_super_glam_looking_layne_staley?utm_source=Dangerous+Minds+newsletter&utm_campaign=e621186a85-RSS_EMAIL_CAMPAIGN&utm_medium=email&utm_term=0_ecada8d328-e621186a85-65849149 in shaarli (updated to last vesion) and shaarli save this:
http://dangerousminds.net/comments/a_super_glam_looking_layne_staley&utm_term=0_ecada8d328-e621186a85-65849149
this is bad, right? a bug? or something?

**Comment by nodiscc** [comment]
@nicolasdanelon Thank you, patch at https://github.com/shaarli/Shaarli/pull/314

**Comment by nicolasdanelon** [comment]
@nodiscc do you think is possible or useful to create *something* to cleanup database information? tags and parameters of url.. missing HTML entities in descriptions and somethings like that?

**Pull request merged**
