### PR TITLE
add shaarli-default-dark to the themes list

### PR DESCRIPTION
**Pull request by xfnw**

### CODE REVIEW

**Comment by nodiscc** [comment]
@xfnw  I cherry-picked your commit and added it to #1389. I just need some time to test all install methods/variants before I can merge it. Thanks for the patch!

**Comment by ArthurHoaro** [comment]
I wouldn't recommend to maintain a whole theme if you only changed colors though.
I think this can be achieved either using a custom user CSS file or the `default_colors` plugin.

**Comment by agentcobra** [comment]
The solution :
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by nodiscc** [comment]
Suggested only using custom CSS to implement these changes at https://github.com/xfnw/shaarli-default-dark/issues/1

**Comment by agentcobra** [comment]
link with #1811

**Pull request closed without merging**
