### PR TITLE
restore original initial link seed timestamp. fixes regression 598376d

### LINKED ISSUE #347: missing Atom feed cache invalidating after adding link
The 0.5.* versions until current `master` seem to have a cache invalidation bug after adding a new link.

See https://github.com/mro/Shaarli-API-test/issues/1#issuecomment-138123795

See all failing builds under so called 'allowed failures* in https://travis-ci.org/mro/Shaarli-API-test/builds/79034284

### PR DESCRIPTION
**Pull request by mro**
… [598376d4cfe](https://github.com/shaarli/Shaarli/commit/598376d4cfeab52cb7aaefa0d553f74f603bad9b#commitcomment-13090918). See my comment there. Fixes #347 and https://github.com/mro/Shaarli-API-test/issues/1, see [integration test result](https://travis-ci.org/mro/Shaarli-API-test/jobs/79080655)

### CODE REVIEW

**Comment by mro** [comment]
Fixes the bug: https://travis-ci.org/mro/Shaarli-API-test/jobs/79080655

**Comment by virtualtam** [comment]
- I wouldn't consider #238 as a _regression_ -it is more user-friendly to create default links with a timestamp corresponding to the creation of the Shaarli instance
- a perfectly acceptable _improvement_ to ease testing (because this is rather a testability issue than a Shaarli defect) would be to create default links using an oldest timestamp, e.g.
 - _current datetime minus 1 minute_ for the public link
 - _current datetime minus 2 minutes_ for the private link

**Comment by ArthurHoaro** [comment]
I agree with @virtualtam. Your problem isn't really about default link timestamp, but that you can't create 2 links in 1 sec time frame.

**Comment by mro** [comment]
@virtualtam I don't follow your argument, but want to get the fix accepted. IMO that's not a matter of user-friendliness but personal taste (a frequent mistake). Fair enough there's many potential *historic* dates that make a certain sense, including the installation time.

Yes, it's likely that the issue never appears in a manual installation setting, but that's IMO a restriction that could be discussed.

But: the `historic` versions work, the recent don't. That's my understanding of a bug. Just it's not user-facing.

So please, accept a fix.

**Comment by ArthurHoaro** [comment]
This is only a workaround, but I'm ok with it. Can you squash your commits?

**Comment by virtualtam** [comment]
> So please, accept a fix.

This PR does not fix anything but the currently _biased_ test sequence of _Shaarli-API-test_.

> the historic versions work, the recent don't

Consecutively adding two links on _any_ version of Shaarli, without waiting for the necessary second, will fail.

Whether it happens at step `n` or `n+1` of the testing iteration has no relevance: the _actual issue_ is still here, and remains to be tackled with - #351 raised to this effect.

Were the test suite actually representative of a real-life Shaarli interaction, it would need to add several links on-the-fly, and test the correct data is held in the datastore, which will not work without waiting for a second between two additions - suggested in mro/Shaarli-API-test/pull/3.

> that's not a matter of user-friendliness but personal taste

The interface you provide users with when they first install a piece of software matters. This might be a totally subjective notion, but keep in mind that software is intended for _humans_, not for _automated test_ suites.

**Comment by mro** [comment]
@virtualtam said [Sept 7th, 11:33:](https://github.com/shaarli/Shaarli/pull/348#issuecomment-138250922)
> a perfectly acceptable improvement to ease testing (because this is rather a testability issue than a Shaarli defect) would be to create default links using an oldest timestamp, e.g.
>
> - current datetime minus 1 minute for the public link
> - current datetime minus 2 minutes for the private link

so the code change in the PR is exactly what you proposed. Is it still acceptable or changed your mind between Sept 7th, 11:44 and Sept 8th, 21:16?

**Comment by ArthurHoaro** [comment]
Closing this since it's a workaround for a 3rd party tool, which shouldn't affect Shaarli's core code.

Regarding the issue, #351 has been opened.

**Pull request closed without merging**
