### PR TITLE
Rename (inc/) & Move (rain.tpl)

### PR DESCRIPTION
**Pull request by nicolasdanelon**
Rename /inc folder & moved RainTPL to app folder

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
A few changes are required:

  * Blazy link in picwall template has not been updated.
  * please update path in COPYING.
  * Documentation mention to `inc/` needs to be updated.

This aside, I don't see any problem.

**Comment by nodiscc** [comment]
@nicolasdanelon can you fix the mentioned points and rebase on top of master? Thanks

**Comment by nicolasdanelon** [comment]
Yes I will :)

**Comment by nodiscc** [comment]
After having another look I don't see the point of moving ic -> assets. I think I'll just cherry-pick https://github.com/nicolasdanelon/Shaarli/commit/15f092e7fd42ddaf077e87f31c0c5fc674ea4b75

**Comment by nicolasdanelon** [comment]
@nodiscc I'm done with @ArthurHoaro corrections. The deal is ''inc/'' folder is not a generic name for CSS and Javascript files

**Comment by nicolasdanelon** [comment]
Please take a look to the first link, and the others too
http://stackoverflow.com/questions/24199004/best-practice-to-organize-javascript-library-css-folder-structure
http://stackoverflow.com/questions/2071687/naming-convention-for-assets-images-css-js
http://www.yiiframework.com/wiki/148/understanding-assets/

**Comment by nicolasdanelon** [comment]
And please take a good look for nicolasdanelon@cac59e9

**Comment by nodiscc** [comment]
Thank you. I merged the duplicate id fix and the CSS fix.
`inc/` is now a standard directory for storing css/js/images.

**Comment by nicolasdanelon** [comment]
If  inc/ is now a standard directory for storing css/js/images we need to remove rain.tpl.class.php file from there, we got a application folder for that, right?

**Comment by nodiscc** [comment]
Right, rain.tpl.class.php should be moved

**Pull request closed without merging**
