### PR TITLE
Selection is now limited to 2k characters using bookmarklets

### LINKED ISSUE #528: Bookmarklet should limit the size of the description in order not to hit maximum length of HTTP GET request
Hi,

For example:

```
GET /links/?post=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DSYRlTISvjww&title=Uptime%20
Funk%20-%20(Uptown%20Funk%20parody)%20-%20YouTube&description=%22Uptime%20Funk%22%20music%20video%20(parody%20of%20Uptown%20Funk)%20from
%20SUSECon%202015%20in%20Amsterdam.%0A%0ALyrics%3A%0AThis%20bit%0AUncontrolled%0AA%20bad%20bug%2C%0AMake%20my%20system%20fold%0AThis%20b
ug%2C%20in%20the%20kernel%0AMy%20kernel%0AMy%20uptime%20ceases%0AFreakin%E2%80%99%2C%20Spazzin%E2%80%99%0AMy%20manager%E2%80%99s%20mad%2
C%20it%20ain%E2%80%99t%20pretty%0AI%20need%20caffeine%2C%20a%20big%20screen%0AGotta%20fix%20this%20server%20in%20a%20jiffy%0A%0AIt%E2%80
%99s%20too%20hot%20(hot%20patch)%0ACall%20Torvalds%20and%20Kroah-Hartman%0AIt%E2%80%99s%20too%20hot%20(hot%20patch)%0AMake%20a%20Sys%20A
dmin%20retire%20man%0AIt%E2%80%99s%20too%20hot%20(hot%20patch)%0AHoly%20cow%2C%20am%20I%20in%20a%20jam%0AIt%E2%80%99s%20too%20hot%20(hot
%20patch)%0ATellin%27%20ya%20now%20it%20ain%27t%20that%20funny%0AServer%27s%20down%0A%0ALive%20patching%20hallelujah%20(whoo)%0ALive%20p
atching%20hallelujah%20(whoo)%0ALive%20patching%20hallelujah%20(whoo)%0A%E2%80%98Cause%20Uptime%20Funk%20gon%E2%80%99%20give%20it%20to%2
0ya%0A%E2%80%98Cause%20Uptime%20Funk%20gon%E2%80%99%20give%20it%20to%20ya%0A%E2%80%98Cause%20Uptime%20Funk%20gon%E2%80%99%20give%20it%20
to%20ya%0ASaturday%20night%20and%20servers%20alright%0ADon%E2%80%99t%20reboot%20it%20just%20patch%20(come%20on)%0ADon%E2%80%99t%20reboot
%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%
20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0AHey%2C%20hey%2C%20hey%2C%20oh%0A%0AHalt%0ADon%E2%80%99t%20reboot%2C%20init%0AFound%20a%20fix%2C%20grab%20code%20from%20git%0AMake%20a%20build%2C%20passed%20the%20tests%0AJulio!%20Make%20a%20patch!%0ARide%20to%20Provo%2C%20Nuremberg%2C%20Newbury%20in%20the%20UK%0AWe%20got%20Linux%2C%20and%20there%27s%20no%20doubt%0AGonna%20fix%20that%20server%20in%20a%20jiffy%0A%0AI%27m%20all%20green%20(hot%20patch)%0ACalled%20a%20Penguin%20and%20Chameleon%0AI%27m%20all%20green%20(hot%20patch)%0ACall%20Torvalds%20and%20Kroah-Hartman%0AIt%E2%80%99s%20too%20hot%20(hot%20patch)%0AYo%2C%20say%20my%20name%20you%20know%20who%20I%20am%0AIt%E2%80%99s%20too%20hot%20(hot%20patch)%0AI%20ain%27t%20no%20simple%20code%20monkey%0ANuthin%27s%20down%0A%0ALive%20patching%20hallelujah%20(whoo)%0ALive%20patching%20hallelujah%20(whoo)%0ALive%20patching%20hallelujah%20(whoo)%0A%E2%80%98Cause%20Uptime%20Funk%20gon%E2%80%99%20give%20it%20to%20ya%0A%E2%80%98Cause%20Uptime%20Funk%20gon%E2%80%99%20give%20it%20to%20ya%0A%E2%80%98Cause%20Uptime%20Funk%20gon%E2%80%99%20give%20it%20to%20ya%0ASaturday%20night%20and%20servers%20alright%0ADon%E2%80%99t%20reboot%20it%20just%20patch%20(come%20on)%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0AHey%2C%20hey%2C%20hey%2C%20oh!%0A%0ABefore%20we%20leave%0AImma%20tell%20y%27all%20a%20lil%20something%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0AI%20said%20Uptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0A%0ACome%20on%2C%20patch%0AGet%20on%20it%0AIf%20you%20stable%20then%20flaunt%20it%0AIf%20you%20online%20then%20own%20it%0ADon%27t%20text%20about%20it%2C%20come%20show%20me%0ACome%20on%2C%20patch%0A%0AGet%20on%20it%0AIf%20you%20stable%20then%20flaunt%20it%0AWell%20it%E2%80%99s%20Saturday%20night%20and%20the%20servers%20alright%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0ADon%E2%80%99t%20reboot%20it%20just%20patch%0AHey%2C%20hey%2C%20hey%2C%20oh!%0A%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0A(say%20whaa%3F!)%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0A(say%20whaa%3F!)%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0A(say%20whaa%3F!)%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0AUptime%20Funk%20you%20up%2C%20Uptime%20Funk%20you%20up%0A(say%20whaa%3F!)%0AUptime%20Funk%20you%20up&source=bookmarklet
```

leads to a 502 HTTP error on most webservers. Limit is usually 8192 bytes.

Thanks
J.

### PR DESCRIPTION
**Pull request by ArthurHoaro**
to avoid having too large URL

Fixes #528

### CODE REVIEW

**Comment by pikzen** [comment]
I assume this is due to the generally agreed on idea that URLs should be less than 2000 characters long.
For reference, IE6/7/8/9/10/Edge stops at 2083 characters, other major browsers reach 65k characters without too many issues.

As a slight QoL thing, maybe this could warn the user that their selection is about to be truncated, for clarification?

**Comment by ArthurHoaro** [comment]
Actually no, it's rather for server side errors, as mentioned in the linked issue. I don't think their are a lot of people using Shaarli's bookmarklets with IE. This limit might too low though, I just have no idea what it should be. Making a few tests, PHP built-in server oddly truncates the request, nginx throws a 414 HTTP error at some point. These issues appear way beyond 2k chars, though.

> As a slight QoL thing, maybe this could warn the user that their selection is about to be truncated, for clarification?

Would an ellipsis be enough?

**Comment by pikzen** [comment]
I had typed something this morning, but fat fingered the back button.

The gist of it was, if modifying something the user wants to do (even if it's obviously stupid), make it loud and clear. Ellipsis would be at the end of the description, which is not going to be visible most likely. And probably not checked either ¯\_(ツ)_/¯

This is one of the rare use cases where a simple alert() could probably be justified. It also happens to be the easiest to implement. That or flashing a message on the Shaarli popup, but they may require more changes.

**Comment by nodiscc** [comment]
> Ellipsis would be at the end of the description, which is not going to be visible most likely

This needs to be tested but that was my concern as well. If the end of the description is not visible without scrolling it may lead the users into thinking _all_ their selection was added to the description, when it was not.

If the description field can be scrolled all the way down automatically, an ellipsis `[...]` would be nice. Else an alert box is a good compromise (would not happen very often).

**Comment by ArthurHoaro** [comment]
Thanks for your feedbacks. 

So, I ran further tests:

  * both Apache and nginx default request line limit is 8k
  * on both servers, I reached that limit with an URI around 5.7kB

I can't easily use `substr` on an URL encoded string because it splits encoded characters, creating invalid strings. So I put the limit at an arbitrary 4k characters which should be fine in most cases. Just don't select long chinese text.

I've also added an alert to warn the user, and an ellipsis.

**Pull request merged**
