### PR TITLE
better looking search fields

### PR DESCRIPTION
**Pull request by nodiscc**
add placeholder text for search fields, change button text to magnifying glass

screenshot

Merging on Sunday, March 15 if no one disagrees.

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
:+1:

**Comment by nodiscc** [comment]
I meant March 15  :) edited

**Comment by mrjovanovic** [comment]
Oh, I like it!

**Comment by nodiscc** [comment]
@mrjovanovic I see what you did here :) Yes those are unicode characters. I tested availability of this symbol in default fonts on win xp, win 7, win 8, Debian, os x 10.8. The previous button text was monochrome so it's also not a harsh change. If you want to use more unicode characters, feel free to propose them in a pull request. They'd have to work on most OSs though.

**Comment by mrjovanovic** [comment]
We can still do this, just use an .svg and .png fallback. I think it's a good direction, but we need a separate topic for icons, methinks.

**Pull request merged**
