### PR TITLE
Update docker-compose.yml to use Traefik v2

### PR DESCRIPTION
**Pull request by synoniem**
Traefik v2 has a steap learning curve but after that Traefik v2 offers far more possibilities to add more services easily than v1. This version has been tested by me locally hence the two small changes in the second commit.

### CODE REVIEW

**Comment by synoniem** [comment]
Apparently this pull request is neither desired nor important, so I am closing the pull request.

**Comment by agentcobra** [comment]
> Apparently this pull request is neither desired nor important, so I am closing the pull request.

why?

**Comment by synoniem** [comment]
> > Apparently this pull request is neither desired nor important, so I am closing the pull request.
> 
> why?

Just as I write it. I have opened this pull request 4 weeks ago and nothing is happening. No comments, no suggestions for correcting or enhancing the script, nothing. It is far more easier for me to merge the extra branch in my fork from Shaarli than to wait for something that maybe in a far future will be merged in  the original. And no need to write new documentation for docker compose too as I am the sole user.

**Comment by nodiscc** [comment]
Hi, I personally don't use the docker-compose based setup (or the docoker-baed one) at all. So I would need to set up a testing environment just for this, which I'm not likely to do very soon. Thanks anyway for the patch, as you noted there would still be some more work to do (documentation, etc), and there doesn't seem to be much interest from other users (or complaints about the current traefik v2 based setup) or maintainers, so I'm not sure it is worth the effort in the current state. If it ain't broke, don't fix it :)

This PR can still be reopened/revisited later for future reference.

Thanks again.

**Pull request closed without merging**
