### PR TITLE
filter input search responsive fixed (mobile) need to merge ASAP

### PR DESCRIPTION
**Pull request by nicolasdanelon**
Need to merge
When merge my responsive fix with ArthurHoaro/search-tag-awesomplete  the mobile layout broke..
Imgur

### CODE REVIEW

**Comment by nicolasdanelon** [comment]
screen shot 2015-06-23 at 11 17 38

**Comment by ArthurHoaro** [comment]
Good catch. It works.

Also, I found another bug. If JS is disabled, the desktop layout is broken. Can you fix it easily here or do you want me to open an issue?

**Comment by nicolasdanelon** [comment]
Yes, sure. Let me fix it.

**Comment by nicolasdanelon** [comment]
done!

**Comment by nodiscc** [comment]
:+1:  thank you. I did not re-test after merging ArthurHoaro/search-tag-awesomplete

**Comment by nodiscc** [comment]
See https://github.com/shaarli/Shaarli/issues/235

**Comment by ArthurHoaro** [comment]
Thanks @nicolasdanelon.

However you edited `awesomplete.css` which comes from https://github.com/LeaVerou/awesomplete. It's not really a good idea if we want to upgrade the dependency.

**Comment by nicolasdanelon** [comment]
@nodiscc thanks, and sorry for my poor testing.
@ArthurHoaro yes, you are right. Because of that (in my first commit) I start editing awesome.css and the I remove my changes.
Working on this, now! thanks

**Pull request merged**
