### PR TITLE
Update README and Shaarli's footer

### PR DESCRIPTION
**Pull request by nodiscc**
* remove version number display from main page
 * update project URL in footer, fixes https://github.com/shaarli/Shaarli/issues/89
 * update copyright notice in the footer
 * mention origins of the fork in README, fixes https://github.com/shaarli/Shaarli/issues/105
 * update License section in the README
 * remove screenshots as mediacru.sh is down

### CODE REVIEW

**Comment by pikzen** [comment]
http://blog.idleman.fr/ is no longer credited in the footer nor in COPYING for the original theme. Perhaps it should be added ?

**Comment by nodiscc** [comment]
I had to update info in COPYING as it missed credits to idleman for the original CSS, and Yahoo Inc. for the CSS reset. reset and main CSS were split in 2 distinct files. @e2jk agree to merge?

**Comment by e2jk** [comment]
I would remove the "wish" part in the sentence

    he would have no time/wish to work on Shaarli

I think that fundamentally @sebsauvage still wants to work on Shaarli, but just that he doesn't have the time.

2 bits regarding the link to "Shaarli community" in the footer:
- Put the space out of the link
- Link to the root of the github repository instead of the COPYING file. This link is not meant to be a list of contributors, but to the homepage of the product, as was the case with the old link to the wiki page.

Since this pull request is touching copyright information, please add a mention of RainTPL. This is how I have it documented in the [Debian package](http://anonscm.debian.org/cgit/collab-maint/shaarli.git/tree/debian/copyright) (I notice that the upstream file now contains more information about all the logos, I'll need to update my Debian file accordingly):

```
Files: inc/rain.tpl.class.php
Copyright: 2011-2012, Federico Ulfo <rainelemental@gmail.com>
           2011-2012, The Rain Team <hello@raintm.com>
License: LGPL-3+
```

**Comment by nodiscc** [comment]
@e2jk I fixed the points you mentioned. Let me know if this is ok to merge, I'd like to squash the commits to only have 2 in the history (`Update README and Shaarli's footer` and `Fix missing authors and licenses in COPYING`) befor merging.

**Comment by e2jk** [comment]
Yes, looks good. Go ahead with commit squashing.

**Comment by nodiscc** [comment]
Merged, thanks.

**Pull request merged**
