### PR TITLE
encondig issues.. font size

### PR DESCRIPTION
**Pull request by nicolasdanelon**
fixing my latest issue #171 ... i found a wrong font size in the add link input because of that there's to commits in this merge request

### CODE REVIEW

**Comment by nodiscc** [comment]
@nicolasdanelon I had another solution in #171 which was just to revert the change to unicode symbols. **But**

1. do you see a proper "magnifying glass" symbol when you use `&#128269;` instead of the `🔍` symbol I used?
2. What's the problem with font size? I don't understand waht https://github.com/nicolasdanelon/Shaarli/commit/d5c033116cf01cfa0ae7dc92b1d50dd708435d9d does.

**Comment by nicolasdanelon** [comment]
Is different in addlink page. Is too small

**Comment by nicolasdanelon** [comment]
Change from 10pt to 8pt

**Comment by nodiscc** [comment]
> Is different in addlink page. Is too small
> Change from 10pt to 8pt

I don't have this problem. All font sizes are the same for me, on all pages. Please make sure you are using the latest `master` form here without modifications, and telle us if this happens again.

Does using HTML entities fix the search field symbol problem?

**Comment by nicolasdanelon** [comment]
I'm on master. And I am not caching :)
Html entities doesn't work.. I use two linux machines for test :(

**Comment by nicolasdanelon** [comment]
Please check font size in addlink page. The input has the same class that
links in home page. With 8pt, that's fine for links in homepage but not for
that input. Is no readable and lost consistent with other inputs in website

**Comment by nicolasdanelon** [comment]
I'm talking about add link page manuall without any plugin or boockmark
link :)

**Comment by nodiscc** [comment]
Ok I see the font-size problem now, thanks. Will be fixed as soon as possible.

**Comment by nicolasdanelon** [comment]
should i delete this pull request?

**Pull request closed without merging**
