### PR TITLE
add meta tag to block sending the referrer

### PR DESCRIPTION
**Pull request by fpunktk**
Add a meta tag that tells the browser not to send the referrer header.

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Does this override #690?

**Comment by nicolasdanelon** [comment]
@ArthurHoaro I found this http://stackoverflow.com/a/11782281

**Comment by nodiscc** [comment]
So this patch is about a Search Engine Optimization choice (tell teh crawlers that your Shaarli and the linked sites are not related), whereas #690 is about improving Shaarli visitors privacy (don't send the HTTP refferer when clicking on a link).

@fpunktk is this correct?

If I understood properly, I'd be ok with both changes.

**Comment by ArthurHoaro** [comment]
No, @nicolasdanelon's link is not really related to this (it's talking about how googlebot will behave with the `nofollow` directive regarding the referrer).

From what I understand (I didn't know about it until now), it's more or less the same thing as #690, but it applies globally instead of individual links, which I feel is cleaner. However, it can't be merged as it is, because we use the referrer internally for better redirections.

But there are policies which could fit our usage (keep the referrer internally, and not send it to external domains). I didn't check which one exactly we should use, but it might be a bit better than #690.
Reference: https://w3c.github.io/webappsec-referrer-policy/#referrer-policies

**Comment by fpunktk** [comment]
@nodiscc no, but @ArthurHoaro is correct. 
I've been using this meta tag in my shaarli instance and did not have any problems. But I see that it might break internal redirection functionality. So I think "same-origin" is the correct policy here. 
In the end this is used for privacy reasons (not disclosing the location and usage of shaarli to any linked site). Setting the meta-tag applies to all links, #690 might not catch all links.

**Comment by ArthurHoaro** [comment]
> I've been using this meta tag in my shaarli instance and did not have any problems.

It's used on minor stuff you might not notice. For example, if you edit a link from search results, you should get back to your search results after edition.

> So I think "same-origin" is the correct policy here. [...] Setting the meta-tag applies to all links, #690 might not catch all links.

I agree. Could you edit your PR and squash your commits?

**Comment by fpunktk** [comment]
@ArthurHoaro I change the PR, but I'm not sure whether the squash worked as expected...

**Comment by ArthurHoaro** [comment]
Thanks! Apparently not. :)

```
git rebase -i HEAD~3
# Change the last two 'pick' to 's' or 'squash'. Save.
# Edit your commit message. Save.
git push origin patch-1 --force
```

**Comment by fpunktk** [comment]
After fucking everything up I think I've done it now :-)

**Comment by ArthurHoaro** [comment]
Sorry for the trouble, thanks again!

**Comment by fpunktk** [comment]
No problem, I've learned something in the process :-)

**Pull request merged**
