### PR TITLE
Add CHANGELOG.md

### PR DESCRIPTION
**Pull request by virtualtam**
Closes https://github.com/shaarli/Shaarli/issues/663
See http://keepachangelog.com/en/0.3.0/
See http://sebsauvage.net/wiki/doku.php?id=php:shaarli:history

This file mirrors the content of the Shaarli release notes available at
https://github.com/shaarli/Shaarli/releases

TODO:
- [x] add published Shaarli Community releases
- [x] add unpublished Shaarli Community releases
- [x] add legacy releases from http://sebsauvage.net/wiki/doku.php?id=php:shaarli:history
- [x] check/improve formatting
- [x] look for dead links
- [x] add extra information
    - [x] some missing legacy release dates & links can be gathered from [Sebsauvage's blog](http://sebsauvage.net/rhaa/?q=shaarli)
- [x] add an "Unreleased" entry featuring current changes - v0.8.1
- [x] update https://github.com/shaarli/Shaarli/wiki/Release-Shaarli

### CODE REVIEW

**Comment by virtualtam** [comment]
Preview at https://github.com/virtualtam/Shaarli/blob/changelog/CHANGELOG.md

**Comment by ArthurHoaro** [comment]
Impressive work. :open_mouth:

It can be interesting to add the first release date, v0.0.7beta - [2011-09-16](http://sebsauvage.net/rhaa/index.php?2011/09/16/09/29/58-adieu-delicious-diigo-et-stumbleupon-salut-shaarli-).

**Comment by virtualtam** [comment]
Good point! Didn't think of looking at Sebsauvage's blog entries for extra info :p

**Comment by virtualtam** [comment]
@nodiscc @ArthurHoaro : I've started a release draft at https://github.com/shaarli/Shaarli/releases/tag/untagged-c28b3b43d765ab808d2c

I'd suggest keeping both the GH release draft and the changelog up-to-date on a "major change/fix" merged" basis :)

**Comment by ArthurHoaro** [comment]
Yes, that's a good idea. With this, the master branch contains the changelog for its current state. OK to merge for me.

**Pull request merged**
