### PR TITLE
Docker: move Dockerfiles to the main repository

### PR DESCRIPTION
**Pull request by virtualtam**
Relates to #420

### CODE REVIEW

**Comment by nodiscc** [comment]
You are including ` docker/shaarli-dev/phpinfo.php ` which will cause information disclosure for people who install Shaarli via `git clone`

**Comment by virtualtam** [comment]
Thanks!

PR updated as follows:
- `.htaccess` added for Apache users
    - Nginx users should follow the server configuration page to only enable `index.php` to be run
    - not sure about lighthttpd though
- documentation removed, to be added as a new wiki page
- Dockerfile folders renamed after their usage (production/development)

**Comment by ArthurHoaro** [comment]
I don't really understand why you need the `phpinfo` file at all. Maybe it was just for setting up the docker image itself?

**Comment by virtualtam** [comment]
It's actually quite convenient to have some additional/debug info regarding PHP and installed/enabled modules without having to log in to the (dev) container :)

To avoid introducing this PHP script in the repository, it can be created directly from the Dockerfile, e.g.
```dockerfile
RUN echo "<? php phpinfo(); ?>" > /var/www/index.php
```

instead of:
```dockerfile
COPY phpinfo.php /var/www/index.php
```

**Comment by virtualtam** [comment]
PR updated, images build and run fine: https://hub.docker.com/r/virtualtam/shaarli/builds/

**Pull request merged**
