### PR TITLE
update docker images to use PHP 8

### PR DESCRIPTION
**Pull request by nodiscc**
- fixes https://github.com/shaarli/Shaarli/issues/1868
- tested successful build with `docker build .`
- did not test building the armhf image due to https://github.com/shaarli/Shaarli/issues/1048
- did not test deploying/running the updated image, Docker users please test

### CODE REVIEW

**Review by ArthurHoaro — CHANGES_REQUESTED** [review]
Checking with quick local build, you need to update `.docker/services.d/php-fpm/run` executable to `php-fpm8`.

**Review by virtualtam — COMMENTED** [review]
Main image tested locally :heavy_check_mark: 

After running some quick tests, the Alpine test image does not seem to provide a environment suitable to running tests, which may point to potential issues with the main image:

- the `test` targets depend on the the `translate` target, which fails due to using `find`'s `execdir` flag
- 322 tests fail with PHP parsing errors (this may be related to the currently pinned PHPUnit version)
- 7 tests fail with errors related to filesystem permissions (IIRC this is not new and dates back to running test suites on Alpine images)

I'm attaching the output of:

```shell
$ vendor/bin/phpunit --bootstrap tests/bootstrap.php --testsuite unit-tests
```

for reference.

[tests.log](https://github.com/shaarli/Shaarli/files/9485322/tests.log)

**Comment by nodiscc** [comment]
I also get these results with

```bash
git clone -b docker-alpine-php8 https://github.com/shaarli/Shaarli
cd Shaarli
sudo docker build -f tests/docker/alpine316/Dockerfile .
# Successfully built 8b37e75ac81f
sudo docker run -it --rm --mount type=bind,source=/home/user/Shaarli,destination=/shaarli 8b37e75ac81f /bin/sh
/shaarli # make test
```

- Busybox's [find](https://manpages.debian.org/bullseye/busybox-static/busybox.1.en.html#find) does not support `-execdir`, makefile target must be rewritten
- PHPUnit failures: is PHPUnit supposed to support PHP8 at all? Only PHP7 is mentioned at https://phpunit.de/getting-started/phpunit-9.html

**Comment by nodiscc** [comment]
After setting in `composer.json`

```json
    "require-dev": {
        ...
        "phpunit/phpunit": "^8.0 || ^9.0"
```

and running `composer update --ignore-platform-req=php`, we are down to 7 failures:

```
/shaarli # make test
-------
PHPUNIT
-------
PHPUnit 9.5.24 #StandWithUkraine

Warning:       No code coverage driver available
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

..F............................................................  63 / 982 (  6%)
............................................................... 126 / 982 ( 12%)
............................................................... 189 / 982 ( 19%)
............................................................... 252 / 982 ( 25%)
............................................................... 315 / 982 ( 32%)
............................................................... 378 / 982 ( 38%)
............................................................... 441 / 982 ( 44%)
............................................................... 504 / 982 ( 51%)
............................................................... 567 / 982 ( 57%)
............................................................... 630 / 982 ( 64%)
.........F.F......F............................................ 693 / 982 ( 70%)
............................................................... 756 / 982 ( 76%)
.....................................F......................... 819 / 982 ( 83%)
............................................................... 882 / 982 ( 89%)
............................................................... 945 / 982 ( 96%)
E.........................F..F.......                           982 / 982 (100%)

Time: 00:02.751, Memory: 38.00 MB

There was 1 error:

1) Shaarli\Security\LoginManagerTest::testCheckCredentialsFromUnreachableLdap
Error: Call to undefined function Shaarli\Security\ldap_connect()

/shaarli/application/security/LoginManager.php:201
/shaarli/application/security/LoginManager.php:212
/shaarli/application/security/LoginManager.php:154
/shaarli/tests/security/LoginManagerTest.php:341
/shaarli/vendor/bin/phpunit:123

--

There were 7 failures:

1) Shaarli\HistoryTest::testConstructNotWritable
Failed asserting that exception of type "Exception" is thrown.

/shaarli/vendor/bin/phpunit:123

2) Shaarli\Helper\FileUtilsTest::testWriteWithoutPermission
Failed asserting that exception of type "Shaarli\Exceptions\IOException" is thrown.

/shaarli/vendor/bin/phpunit:123

3) Shaarli\Helper\FileUtilsTest::testWriteFolderPermission
Failed asserting that exception of type "Shaarli\Exceptions\IOException" is thrown.

/shaarli/vendor/bin/phpunit:123

4) Shaarli\Helper\FileUtilsTest::testClearFolderOutsideOfShaarliDirectory
Failed asserting that exception of type "Shaarli\Exceptions\IOException" is thrown.

/shaarli/vendor/bin/phpunit:123

5) Shaarli\Updater\LegacyUpdaterTest::testWriteUpdatesFileNotWritable
Failed asserting that exception of type "Exception" is thrown.

/shaarli/vendor/bin/phpunit:123

6) Shaarli\Updater\UpdaterTest::testReadEmptyUpdatesFile
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
+    0 => 'test'
 )

/shaarli/tests/updater/UpdaterTest.php:75
/shaarli/vendor/bin/phpunit:123

7) Shaarli\Updater\UpdaterTest::testWriteUpdatesFileNotWritable
Failed asserting that exception of type "Exception" is thrown.

/shaarli/vendor/bin/phpunit:123

ERRORS!
Tests: 982, Assertions: 4145, Errors: 1, Failures: 7.
make: *** [Makefile:69: test] Error 2
```

**Comment by ArthurHoaro** [comment]
Great job!

For the LDAP error, it's probably just missing `php8-ldap`. BTW, we should probably add it in the main image as well if we want that feature to be available when installing Shaarli through our Docker, right?

The other issues seem all related to permissions. My guess is that the tests run as root, so it doesn't raise permission issues like it would with a regular user. I'm not sure what's the best approach here.

Depending on how easy it is to fix, since the main image build is broken, it could maybe make sense to merge it first and fix the tests Dockerfiles later?

**Review by virtualtam — APPROVED** [review]
LGTM :+1:

**Comment by virtualtam** [comment]
> The other issues seem all related to permissions. My guess is that the tests run as root, so it doesn't raise permission issues like it would with a regular user. I'm not sure what's the best approach here.

I did similar work for another project to setup reference Debian and Ubuntu environments with Docker and run builds as an unprivileged user: https://github.com/virtualtam/ccache_exporter/tree/main/integration

> merge it first and fix the tests Dockerfiles later

Agreed, I'll see how I can port the aforementioned work so we can run PHP tests using unprivileged users :+1:

**Comment by jlkDE** [comment]
I just tried out this PR to fix my personal container build of Shaarli, so far everything seems to work, good job!
One thing I noticed is that the date format of entries changed: From `30. Januar 2022 um 12:44:20 UTC *` in my case to simply `2022 M01 30 12:44:20 UTC *`.

**Comment by nodiscc** [comment]
> For the LDAP error, it's probably just missing php8-ldap

-> https://github.com/shaarli/Shaarli/issues/1890

> merge it first and fix the tests Dockerfiles later

Let's merge it as-is and tackle remaining problems in separate issues. Thanks for your help.

**Pull request merged**
