### PR TITLE
Include documentation

### PR DESCRIPTION
**Pull request by nodiscc**
Fixes https://github.com/shaarli/Shaarli/issues/149

### CODE REVIEW

**Comment by nodiscc** [comment]
I just cloned `https://github.com/shaarli/Shaarli.wiki.git` to the `doc/` directory, deleted `doc/.git/` and added the directory to the git repo. To sync it again, just delete the doc directory and repeat.

A link in the footer points to the local copy of the doc. Mardown rendering is done via `doc/index.html` from the [mdwiki](https://github.com/Dynalon/mdwiki) project.

**Comment by virtualtam** [comment]
Would it be possible to add the `doc` folder as a Git submodule?

This would avoid manually keeping docs in sync with `Shaarli.wiki.git`. i don't know if GitHub fetches submodules when downloading the repository as a Zip archive, though...

Another option is to add a `make` target that does all the job:
```makefile
# remove all unversioned files
clean:
        @git clean -df

# the target will fail if there are no changes (nothing to commit)
doc: clean
        @rm -rf doc
        @git clone https://github.com/shaarli/Shaarli.wiki.git doc
        @rm -rf doc/.git
        @git add doc/*
        @git commit -s
```

**Comment by nodiscc** [comment]
@virtualtam submodules were my first thought :) Unfortunately Github uses the `git archive` command to generate zipballs, so that doesn't include submodules. We'd have to change the release process to achieve that (ie. [manually attaching arbitrary zip files to releases](https://github.com/blog/1547-release-your-software)) if we want to keep distributing a .zip.

the make target is a great idea.

**Comment by nodiscc** [comment]
Added Makefile targets as suggested, set commit author to @virtualtam.

**Comment by ArthurHoaro** [comment]
I believe it would be better to do this the other way around: sync the doc from the code repo to the wiki repo. It would allow people to make documentation PR.

**Comment by nodiscc** [comment]
Well contributing to the wiki is easier than using Pull Requests for people (even more if they're not used to Github) and we already had a few drive-by contributions to it (can't remember who translated remaining stuff, but thanks). I think it's better to sync the wiki --> official `doc/` from time to time, and manually review changes.

I'll remove the automatic `git add` so we have to manually `git diff doc/` / `git add --patch doc/` during doc updates, to review changes before they go the the official doc.

**Comment by ArthurHoaro** [comment]
Yes, nevermind. I didn't think everybody was able to edit the wiki.

**Pull request merged**
