### PR TITLE
RainTPL: upgrade to 3.1.0, install through Composer

### PR DESCRIPTION
**Pull request by virtualtam**
Relates to https://github.com/shaarli/Shaarli/issues/613

Modifications:
- update `Rain\Tpl` initialization code:
  - autoload with Composer
  - update configuration
  - set 'auto_escape' to false
- [template] reference static resources relatively to the index page,
                 not to the template file anymore,
                 e.g. '../inc/script.js' becomes 'inc/script.js'
- [template] linklist: move "link updated date" processing to PHP code

RainTPL 3.1 specificities:
- no complex variable processing in templates:
  - `{$var1=$var2}` works
  - `{$var1=$condition ? 'Value1' : 'Value2'}` does not
- path to static resources are now relative to the index page

WIP:
- check PHP compatibility
- check all pages work properly

### CODE REVIEW

**Comment by virtualtam** [comment]
PR available for testing, feedback is welcome as there may be some minor quirks due to the RainTPL version bump ;-)

**Comment by ArthurHoaro** [comment]
> [template] reference static resources relatively to the index page, not to the template file anymore, e.g. '../inc/script.js' becomes 'inc/script.js'

This is a breaking change. Because it means that if I write a template, it will only work under a certain folder/path. BUT, there is a plugin in RainTPL3 code called `PathReplace` (obviously not documented) which fixes this and reproduces the previous behaviour.

By the way, instead of `../inc/script.js`, we should do `inc/script.js#`, but don't work too much on the current templates.

[Few more tests...]

I can't render the footer, because the loop:
```html
{loop="$plugins_footer.endofpage"}
    {$value}
{/loop}
```
contains `fp`, which is blacklisted. I'm not so sure about this update.

**Comment by virtualtam** [comment]
Thanks for the feedback! The PR is still a WIP, it is indeed a good idea to keep the template behaviour as close as the current one not to break 3rd-party templates.

Moving to 3.1 means we can write and publish a Slim-RainTPL bridge/plugin that may be of use for other devs.

I've bumped Composer-related stuff to the 0.9.0 milestone so there's more room for testing.

**Comment by virtualtam** [comment]
Rebased, still needs work regarding template compatibility

**Comment by virtualtam** [comment]
Most pages work, still got issues with variable assignments within nested loops (picwall, tag cloud)

**Comment by ArthurHoaro** [comment]
Crap I lost my message. In short, there is a bug in the parser for the ternary regex. There is a fix in feulf/raintpl3#119, we can open a PR but we should expect it to take long or eventually be ignored so, we can workaround it by either:

  * template workaround: adding `{ignore}{/ignore}` in problematic lines such as https://github.com/shaarli/Shaarli/blob/master/tpl/default/daily.html#L50
  * extend the parser class

**Comment by virtualtam** [comment]
Just tested along 3rd-party themes and it's a total mess :p

Apart from forking the repo and applying the appropriate patches, I don't see any straightforward solution...

If there's no hard feelings about it, I'd rather abandon this PR, then we can invest time in the future to migrate templates to an actively-maintained rendering lib :)

**Comment by ArthurHoaro** [comment]
Well, applying the fix I mentioned, I don't have any issue (tested on material theme). While I'm not happy using an almost unmaintained template engine, I don't see rewriting all official and 3rd party theme as an option.

**Comment by virtualtam** [comment]
I've keep my dev branch opened, should I push it to a new branch on the Shaarli repo so we can do more testing?

**Comment by virtualtam** [comment]
Regarding 3rd-party themes, a more flexible way could be to properly decorrelate template rendering from Shaarli "core" code, so a template might rely on a custom rendering engine. This way, we can move towards a modern lib with minimal impact on 3rd-party template devs and users :)

**Comment by ArthurHoaro** [comment]
We'll see what's the best option when we'll try to play with Slim and templates.

That's... an excellent idea.

**Pull request closed without merging**
