### PR TITLE
Code quality: Makefile to run static code checkers

### PR DESCRIPTION
**Pull request by virtualtam**
Here's a Makefile to run the static analysis tools mentioned in #95.
* Several configurations are available for each tool, I've tried to keep them as relevant as possible.
* Tools are managed with Composer, which is pretty straightforward to use.

There's also a Travis config draft, untested (Travis is currently under maintenance).

Edit: Travis is back! Here's what a build looks like: https://travis-ci.org/virtualtam/Shaarli/builds/52341101

### CODE REVIEW

**Comment by nodiscc** [comment]
This is your travis log/`make` output:

```
Using worker: worker-linux-968a87ce-2.bb.travis-ci.org:travis-linux-11

system_info

Build system information

Build language: php

Build image provisioning date and time

Wed Feb 4 18:22:50 UTC 2015

Operating System Details

Distributor ID: Ubuntu

Description: Ubuntu 12.04 LTS

Release: 12.04

Codename: precise

Linux Version

2.6.32-042stab090.5

Cookbooks Version

23bb455 https://github.com/travis-ci/travis-cookbooks/tree/23bb455

GCC version

gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

Copyright (C) 2011 Free Software Foundation, Inc.

This is free software; see the source for copying conditions. There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version

clang version 3.4 (tags/RELEASE_34/final)

Target: x86_64-unknown-linux-gnu

Thread model: posix

Pre-installed Ruby versions

ruby-1.9.3-p551

Pre-installed Node.js versions

v0.10.36

Pre-installed Go versions

1.4.1

Redis version

redis-server 2.8.19

riak version

2.0.2

MongoDB version

MongoDB 2.4.12

CouchDB version

couchdb 1.6.1

Neo4j version

1.9.4

Cassandra version

2.0.9

RabbitMQ Version

3.4.3

ElasticSearch version

1.4.0

Installed Sphinx versions

2.0.10

2.1.9

2.2.6

Default Sphinx version

2.2.6

Installed Firefox version

firefox 31.0esr

PhantomJS version

1.9.8

ant -version

Apache Ant(TM) version 1.8.2 compiled on December 3 2011

mvn -version

Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)

Maven home: /usr/local/maven

Java version: 1.7.0_76, vendor: Oracle Corporation

Java home: /usr/lib/jvm/java-7-oracle/jre

Default locale: en, platform encoding: UTF-8

OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"

git.checkout

0.23s$ git clone --depth=50 --branch=static-analysis git://github.com/virtualtam/Shaarli.git virtualtam/Shaarli

Cloning into 'virtualtam/Shaarli'...

remote: Counting objects: 628, done.

remote: Compressing objects: 100% (322/322), done.

remote: Total 628 (delta 335), reused 588 (delta 298), pack-reused 0

Receiving objects: 100% (628/628), 857.86 KiB | 0 bytes/s, done.

Resolving deltas: 100% (335/335), done.

Checking connectivity... done.

$ cd virtualtam/Shaarli

$ git checkout -qf f5a38ff44df8772600ec93262bb2732cd2d91196

0.03s$ phpenv global 5.5

$ php --version

PHP 5.5.21 (cli) (built: Feb 11 2015 15:24:34)

Copyright (c) 1997-2014 The PHP Group

Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans

$ composer --version

Composer version 1.0-dev (1d8f05f1dd0e390f253f79ea86cd505178360019) 2015-02-11 11:31:57

install

45.44s$ composer install

Loading composer repositories with package information

Installing dependencies (including require-dev)

- Installing symfony/filesystem (v2.6.4)

Downloading: connection... Failed to download symfony/filesystem from dist: Could not authenticate against github.com

Now trying to download from source

- Installing symfony/filesystem (v2.6.4)

Cloning a1f566d1f92e142fa1593f4555d6d89e3044a9b7

- Installing symfony/config (v2.6.4)

Downloading: connection... Failed to download symfony/config from dist: Could not authenticate against github.com

Now trying to download from source

- Installing symfony/config (v2.6.4)

Cloning a9f781ba1221067d1f07c8cec0bc50f81b8d7408

- Installing symfony/dependency-injection (v2.6.4)

Downloading: connection... Failed to download symfony/dependency-injection from dist: Could not authenticate against github.com

Now trying to download from source

- Installing symfony/dependency-injection (v2.6.4)

Cloning 42bbb43fab66292a1865dc9616c299904c3d4d14

- Installing pdepend/pdepend (2.0.4)

Downloading: connection... Failed to download pdepend/pdepend from dist: Could not authenticate against github.com

Now trying to download from source

- Installing pdepend/pdepend (2.0.4)

Cloning 1b0acf162da4f30237987e61e177a57f78e3d87e

- Installing phpmd/phpmd (2.2.0)

Downloading: connection... Failed to download phpmd/phpmd from dist: Could not authenticate against github.com

Now trying to download from source

- Installing phpmd/phpmd (2.2.0)

Cloning 580e6ca75b472a844389ab8df7a0b412901d0d91

- Installing theseer/fdomdocument (1.6.0)

Downloading: connection... Failed to download theseer/fdomdocument from dist: Could not authenticate against github.com

Now trying to download from source

- Installing theseer/fdomdocument (1.6.0)

Cloning d08cf070350f884c63fc9078d27893c2ab6c7cef

- Installing phpunit/php-timer (1.0.5)

Downloading: connection... Failed to download phpunit/php-timer from dist: Could not authenticate against github.com

Now trying to download from source

- Installing phpunit/php-timer (1.0.5)

Cloning 19689d4354b295ee3d8c54b4f42c3efb69cbc17c

- Installing symfony/console (v2.6.4)

Downloading: connection... Failed to download symfony/console from dist: Could not authenticate against github.com

Now trying to download from source

- Installing symfony/console (v2.6.4)

Cloning e44154bfe3e41e8267d7a3794cd9da9a51cfac34

- Installing sebastian/version (1.0.4)

Downloading: connection... Failed to download sebastian/version from dist: Could not authenticate against github.com

Now trying to download from source

- Installing sebastian/version (1.0.4)

Cloning a77d9123f8e809db3fbdea15038c27a95da4058b

- Installing symfony/finder (v2.6.4)

Downloading: connection... Failed to download symfony/finder from dist: Could not authenticate against github.com

Now trying to download from source

- Installing symfony/finder (v2.6.4)

Cloning 16513333bca64186c01609961a2bb1b95b5e1355

- Installing sebastian/finder-facade (1.1.0)

Downloading: connection... Failed to download sebastian/finder-facade from dist: Could not authenticate against github.com

Now trying to download from source

- Installing sebastian/finder-facade (1.1.0)

Cloning 1e396fda3449fce9df032749fa4fa2619e0347e0

- Installing sebastian/phpcpd (2.0.1)

Downloading: connection... Failed to download sebastian/phpcpd from dist: Could not authenticate against github.com

Now trying to download from source

- Installing sebastian/phpcpd (2.0.1)

Cloning a9462153f2dd90466a010179901d31fbff598365

- Installing squizlabs/php_codesniffer (2.2.0)

Downloading: connection... Failed to download squizlabs/php_codesniffer from dist: Could not authenticate against github.com

Now trying to download from source

- Installing squizlabs/php_codesniffer (2.2.0)

Cloning b301c98f19414d836fdaa678648745fcca5aeb4f

symfony/dependency-injection suggests installing symfony/yaml ()

symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)

symfony/console suggests installing symfony/event-dispatcher ()

symfony/console suggests installing symfony/process ()

symfony/console suggests installing psr/log (For using the console logger)

Writing lock file

Generating autoload files

18.33s$ make all

PHP CODE SNIFFER VIOLATION SOURCE SUMMARY

----------------------------------------------------------------------

STANDARD CATEGORY SNIFF COUNT

----------------------------------------------------------------------

[ ] Generic Files Line length too long 491

[x] Generic Functions Function call argument spacin 401

[ ] PEAR Control structures Control signature 207

[x] Generic Control structures Inline control structure disc 161

[x] PEAR Control structures Multi line condition newline 112

[ ] PEAR Commenting Function comment wrong style 70

[x] Generic White space Disallow tab indent tabs used 67

[x] PEAR White space Scope indent incorrect 52

[x] PEAR White space Scope closing brace line 52

[x] PEAR White space Scope indent incorrect exact 27

[x] PEAR Functions Function declaration brace on 13

[ ] PEAR Commenting Function comment missing 13

[ ] PEAR Naming conventions Valid function name function 11

[x] PEAR Functions Function declaration content 9

[ ] PEAR Naming conventions Valid variable name private n 9

[x] Generic PHP Lower case constant found 7

[x] PEAR Control structures Multi line condition start wi 5

[x] PEAR Control structures Multi line condition close br 5

[x] PEAR Files Including file use require 3

[x] Generic Functions Function call argument spacin 3

[x] Generic Functions Function call argument spacin 3

[ ] PEAR Naming conventions Valid function name private n 3

[ ] PEAR Naming conventions Valid class name start with c 3

[ ] PEAR Commenting Class comment wrong style 3

[x] PEAR Functions Function call signature space 2

[x] PEAR Functions Function call signature space 2

[x] PEAR Control structures Multi line condition space be 2

[x] PEAR Control structures Multi line condition alignmen 2

[x] Generic Functions Function call argument spacin 2

[x] PEAR White space Scope closing brace indent 1

[x] PEAR Functions Function declaration brace sp 1

[x] PEAR Functions Function call signature space 1

[x] PEAR Files Including file brackets not r 1

[x] Generic White space Disallow tab indent non inden 1

[ ] PEAR Commenting File comment wrong style 1

[ ] Generic Naming conventions Upper case constant name cons 1

----------------------------------------------------------------------

A TOTAL OF 1747 SNIFF VIOLATIONS WERE FOUND IN 36 SOURCES

----------------------------------------------------------------------

PHPCBF CAN FIX THE 25 MARKED SOURCES AUTOMATICALLY (935 VIOLATIONS IN TOTAL)

----------------------------------------------------------------------

Time: 2.85 secs; Memory: 46.25Mb

-----------------------

PHP COPY/PASTE DETECTOR

-----------------------

phpcpd 2.0.1 by Sebastian Bergmann.

0.00% duplicated lines out of 2609 total lines of code.

Time: 248 ms, Memory: 19.75Mb

-----------------

PHP MESS DETECTOR

-----------------

19 cleancode
34 codesize
663 controversial
72 design
39 naming
15 unusedcode

The command "make all" exited with 0.

Done. Your build exited with 0.
```

It doesn't provide any useful information for debugging, refactoring, cleaning up code... How can we use it to improve Shaarli?

**Comment by virtualtam** [comment]
It provides stats, in a concise way, about how compliant the code is to clean coding standards.
More detailed output is available, for each tool, with other Makefile targets, and should be kept for local use.

I've been using that kind of utility as a commit hook for some time, and it's great to proof-check your commit/branch status before actually pushing anything anywhere (e.g. local/small projects without code-review services).

Not having details in commit-triggered builds is useful for project managers, to track code evolution trends.

The main goal behind having a Makefile is to easily run unit tests, which is planned for #71. You may then consider having static checkers' concise output as a bonus for your build log :smiley: 

Please note that I'm not assuming everything here is relevant; this PR essentially provides a fashionable way to install and run some popular PHP dev tools.

**Comment by nodiscc** [comment]
Ok, while I see the goal of this PR (better code quality), I'm not ok with merging this in the `master` branch, which is our current _release_ branch.

Dev tools have nothing to do in our released code. The Makefile is definitely useful to run checks locally and work on code quality. A `dev-tools` branch + docs on how to install composer and requirements + docs on how to run checks would be a better place. Or a dedicated wiki page.

**Comment by virtualtam** [comment]
I'm a bit confused...

What would be the point in hiding test code in a development branch? Or even worse, a Wiki page?

Providing test code and utilities along the actual product's codebase is, besides being a standard for all modern projects, a huge asset to improve the quality and quantity of code contributions:
* the presence of tests usually means that a project is being well-cared of;
* designing, writing and running tests should be as straightforward as possible;
* any tool necessary for development and / or helping maintaining a clean codebase should be easily installable and usable by contributors.

Tests are part of -and often more important than- the code: they live with it, show how it (is expected to) work, and should not be kept apart.

There may be a confusion here, between:
* a _release branch_, which is the state the software is when you flag it as _being ready for release_,
* the actual _released product_, which is what the user gets.

Here is an awesome example of [a successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/):
* `master`: stable branch;
* `devel`: development mainline (next release);
* `v1.x`: release branches;
* `feat/topic/feature`: feature branches;
* `fix/topic`: hotfixes.

Given the small size of Shaarli, we could stick to stable, development and release branches.

As I understand it, the issue is having "non-release" code provided to users; why not work on a release script / process then, that would:
* trim dev resources, test code and utilities;
* minify stylesheets, only keep minified Javascript libs;
* build an all-in-one archive, ready for the user to grab and deploy.

**Comment by nodiscc** [comment]
> why not work on a release script / process then, that would

This is something that could be done in the long run. However the current download strategy for users is to either `git clone` the repo, or grab and extract the zipball that github provides. I'd prefer not changing it, regarding the current state of Shaarli where there are already issues that need to be dealt with before thinking about adding external tools like travis.

While the travis integration is nice and automatically gives us a summary of what could be improved on each pull request, _it does not help with the current state of the code_ at all, which _needs_ to be addressed before we can think of best practices for further contributions.

How I'd handle that: first merge the Makefile since it is helpful for cleaning up current code. Provide comments in it on how to install the required tools. Let the composerfile and travis integration wait for later.

**Comment by nodiscc** [comment]
@pikzen seemed to disagree with me in a private chat:

> (17:10:02) Monsieur //pikzen: jpeux comprendre
> (17:10:16) Monsieur //pikzen: c'est pas parce que t'as dla merde sur la chaussure que tu les cire pas

**Comment by pikzen** [comment]
huehuehuehue
I expanded a bit later though. 

For those who do not speak french, it went that way:

```
Monsieur //pikzen: I can understand
Monsieur //pikzen: Having shit under your shoe does not prevent you from polishing it
Monsieur //pikzen: analogy.png
...
Monsieur //pikzen: I mean, you still have shit under your shoe
Monsieur //pikzen: but at least it's polished
```

I definitely agree with providing tools to maintain a high code quality in Shaarli (read: not what there is currently). PHPMD is great (835 problems on the laster master woohoooo), so is phpcs, etc.

What @nodiscc probably didn't understand is that I rather agree with him (which also means that my analogies are terrible): providing the Makefile is great. 
I'm slightly less convinced by Travis because you're only warned once the code is pushed, which makes little sense to me, the push shouldn't have any warning. I can understand that some people might not want to have to install phpmd, phpcs et. al. to contribute to the code. I don't care personally, my dev machine probably has half of debian's packages installed.

Providing an install script is great: we can store whatever the hell we want in master and not have it mirrored when the users install Shaarli.

(As an aside, phpmd reports $GLOBALS usage as a problem, so either ignore it or merge #108 in to fix 300 in one go :trollface:)

**Comment by nicolasdanelon** [comment]
Shaarli runs with PHP 5.1
[Travis-cli PHP 5.4](http://docs.travis-ci.com/user/languages/php/) right ?
[Symfony/Yaml](https://packagist.org/packages/symfony/yaml) PHP 5.5.9
So... is it good for the project ?

**Comment by e2jk** [comment]
I *do* think that having this included in the master repository is the right thing to do. It allows anyone getting the source to reproduce it (which is a core part of the FLOSS philosophy, we're not just dumping a tar-/zipball over the fence every now and then), can be used by Linux distributions to run tests, etc. when building their packages, and provides a way to automatically run these tasks each time a new commit is pushed to GitHub.

As I have explained [elsewhere](https://github.com/shaarli/Shaarli/issues/71#issuecomment-66148252), the original goal of having everything in one file is long gone. And in the worst case the user has a Makefile on their webserver. Not a big deal, they already have these files that are not strictly needed (in the technical sense) to run the software:
- `README.md`
- `.gitignore`
- `COPYING`
- `inc/LICENSE`

**Comment by nodiscc** [comment]
Fine, let's merge it if you think it helps. At least I agree the Makefile helps :)

**Comment by virtualtam** [comment]
Thanks to all for you insights ;-)

> you're only warned once the code is pushed

That's the cool thing, Travis runs builds on any branch that has a `.travis.yml`, and for every pull request (I haven't tested it yet, feel free to submit dummy PRs on my repos to see what happens ^^)

> first merge the Makefile

Agreed. Travis integration was a bonus / demo here, and can be kept for later.

> X runs with PHP 5.Y

Adding expected PHP revisions to Travis is quite easy, I think we can safely focus on `PHP >= 5.4 `, at least as a starter (CI evolves with the software, and is no time machine)

> Provide comments in it on how to install the required tools.

I'd rather provide an actual Composer config file, than a Makefile with lots of superfluous setup comments / instructions.
The aim is to give devs helpful tools, not to hassle them with installing dependencies and setup a test environment.

> my dev machine probably has half of debian's packages installed

4-year-old dev ArchLinux here, quite safe to assume there's a bunch of unused and obsolete stuff lurking in each and every corner :trollface: 

If needed, we could meet by IM to discuss CI PRs (either on Gitter, IRC, XMPP or whatever service is convenient) :smiley:

**Comment by nodiscc** [comment]
@virtualtam @e2jk So what do we keep in this Pull Request before merging?

**Comment by virtualtam** [comment]
I'd:
* keep the Makefile, gitignore and composer files,
* improve usage notes in the Makefile, to better describe which tool does what (though it's quite explicit already),
* start a wiki page, e.g. _How to contribute to Shaarli_, where we'd define some guidelines to follow for PR submission,
* remove the Travis config file, and keep it for an other PR (I've seen it work, which is a pleasant start)

**Comment by nodiscc** [comment]
@virtualtam Ok, please make the required changes and rebase and we can merge. If you want to document the contribution process (in the wiki) it's also welcome, either in a separate page or in a new chapter.

**Comment by virtualtam** [comment]
PR updated ;-)

**Comment by nodiscc** [comment]
Thanks!

**Pull request merged**
