### PR TITLE
Working on shaarli/Shaarli#224

### PR DESCRIPTION
**Pull request by ArthurHoaro**
I reviewed character escaping everywhere with the following ideas:

  * use a single common function to escape user data: `escape` using `htmlspecialchars`.
  * sanitize fields in `index.php` after reading them from datastore and before sending them to templates.
  	It means no escaping function in Twig templates.
    2 reasons:
    * it reduces risks of security issue for future user made templates
    * more readable templates
  * sanitize user configuration fields after loading them.

Please review it carefully since it touches a lot of code.

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
I rebased the commit because I had forgotten to re-enable ATOM feed cache.

**Comment by nodiscc** [comment]
Help needed on merging this :/ @ArthurHoaro can you rebase?
The changes look good

**Comment by ArthurHoaro** [comment]
I'm not sure my merging method was the most efficient, but it should be fine now.

**Comment by nodiscc** [comment]
Thank you.
I had to move escape() and sanitizeLink() to application/Utils.php, the tests raised an error https://github.com/shaarli/Shaarli/commit/64bc92e3ac8f5e66d2bc14206ede31e6679d8c13

**Pull request merged**
