### PR TITLE
Fixes TU and test hidden public link

### LINKED ISSUE #236: tests failing: Undefined index: HIDE_PUBLIC_LINKS
```
$make 
[.....]
-------
PHPUNIT
-------
PHPUnit 4.6.10 by Sebastian Bergmann and contributors.

Configuration read from /tmp/git/Shaarli/phpunit.xml

The Xdebug extension is not loaded. No code coverage will be generated.

PHP Notice:  Undefined index: HIDE_PUBLIC_LINKS in /tmp/git/Shaarli/application/LinkDB.php on line 213
PHP Notice:  Undefined index: HIDE_PUBLIC_LINKS in /tmp/git/Shaarli/application/LinkDB.php on line 213
EE.EEE..E..........................

Time: 486 ms, Memory: 5.00Mb

There were 6 errors:

1) LinkDBTest::testConstructLoggedIn
Undefined index: HIDE_PUBLIC_LINKS

/tmp/git/Shaarli/application/LinkDB.php:213
/tmp/git/Shaarli/application/LinkDB.php:60
/tmp/git/Shaarli/tests/LinkDBTest.php:79

2) LinkDBTest::testConstructLoggedOut
Undefined index: HIDE_PUBLIC_LINKS

/tmp/git/Shaarli/application/LinkDB.php:213
/tmp/git/Shaarli/application/LinkDB.php:60
/tmp/git/Shaarli/tests/LinkDBTest.php:88

3) LinkDBTest::testCheckDBNew
Undefined index: HIDE_PUBLIC_LINKS

/tmp/git/Shaarli/application/LinkDB.php:213
/tmp/git/Shaarli/application/LinkDB.php:60
/tmp/git/Shaarli/tests/LinkDBTest.php:109

4) LinkDBTest::testCheckDBLoad
Undefined index: HIDE_PUBLIC_LINKS

/tmp/git/Shaarli/application/LinkDB.php:213
/tmp/git/Shaarli/application/LinkDB.php:60
/tmp/git/Shaarli/tests/LinkDBTest.php:129

5) LinkDBTest::testReadEmptyDB
Undefined index: HIDE_PUBLIC_LINKS

/tmp/git/Shaarli/application/LinkDB.php:213
/tmp/git/Shaarli/application/LinkDB.php:60
/tmp/git/Shaarli/tests/LinkDBTest.php:151

6) LinkDBTest::testSaveDB
Undefined index: HIDE_PUBLIC_LINKS

/tmp/git/Shaarli/application/LinkDB.php:213
/tmp/git/Shaarli/application/LinkDB.php:60
/tmp/git/Shaarli/tests/LinkDBTest.php:183

FAILURES!
Tests: 35, Assertions: 53, Errors: 6.
Makefile:106: recipe for target 'test' failed
make: *** [test] Error 2
```

### LINKED ISSUE #263: Ajouter deux liens au wiki
Hello !

J'ai codé deux outils (enfin, un est une variation de l'autre), permettant de détecter les liens morts sur les instances shaarlis. Si ça intéressent du monde, pourquoi pas le rajouter au wiki ?

https://github.com/qwertygc/shaarli-dev-code/blob/master/self-dead-link.php
https://github.com/qwertygc/shaarli-dev-code/blob/master/dead-link.php

### PR DESCRIPTION
**Pull request by ArthurHoaro**
Fixes #236

@VirtualTam: to test this, I had to change config in a single test, so I had to regenerate data for every test. I don't feel like it's the best thing to do, but I'm not sure I can do otherwise. Is this OK?

### CODE REVIEW

**Comment by virtualtam** [comment]
The real issue here is accessing a global variable, why not tackle it in this PR? :)

This can be done by injecting the variable to LinkDB's constructor, and pass it as a parameter when instantiating the class.

**Comment by virtualtam** [comment]
I've pushed an example solution, feel free to test it :)

**Comment by nodiscc** [comment]
I've merged @virtualtam's commit https://github.com/virtualtam/Shaarli/commit/5ba31c2f5336664c0afb6c2e03999799e5dbb2a0 into master. Again thank you both for your help.

Tests are now passing, test results available at https://travis-ci.org/shaarli/Shaarli

**Comment by virtualtam** [comment]
@nodiscc you're welcome!
Thanks for enabling Travis as well :)

**Comment by ArthurHoaro** [comment]
Thanks, definitely better!

**Pull request closed without merging**
