### PR TITLE
Use awesomplete as autocomplete lib and remove jQuery - shaarli/Shaarli#148

### PR DESCRIPTION
**Pull request by ArthurHoaro**
* Add awesomplete dependancy (source + min + CSS)
  * Remove jQuery and jQuery-UI dependancy
  * Few CSS ajustements
  * Use tags complete list as RainTPL var (and display it as HTML)
  * Remove "disable jQuery" feature
  * Remove tag list web service

EDIT : And update COPYING.

EDIT2: 
snapshot2 :laughing:

### CODE REVIEW

**Comment by nodiscc** [comment]
Congrats @ArthurHoaro great work!

2 small problems I noticed while testing:
 * The autocompletion dropdown/list background should probably not be transparent (to stay coherent with the general style)
 * Autocompletion should probably start when entering the first character (currently it only starts after 2)

What do you think? Can you fix this? Except these 2 points, everything is fine and

> 563 additions and 27,028 deletions

:metal:

**Comment by nodiscc** [comment]
I think the next step after merging this would be https://github.com/shaarli/Shaarli/issues/49 (re-adding autocompletion to the "Filter by tag" field on the main page

**Comment by nodiscc** [comment]
Another possible improvement is to use `Tab` or `Left Arrow` keys to add the selected suggestion to the contents of the field.

Currently it's only the `Enter` key and can cause mistakenly triggering "Save" when you're not finished editing tags and hit enter when the suggestion doesn't have focus.

**Comment by ArthurHoaro** [comment]
Thanks !

> The autocompletion dropdown/list background should probably not be transparent (to stay coherent with the general style)

It's hardly transparent on my screen, but I guess I can remove this effect.

> Autocompletion should probably start when entering the first character (currently it only starts after 2)

You're right. I'll do this.

About your other improvements, I suggest you mention them on #148.

**Comment by ArthurHoaro** [comment]
Done and rebased.

**Comment by nodiscc** [comment]
Great, testing this right now, I'll merge it on Sunday, March 5 if it works as expected and no one disagrees.

Hats off

**Pull request merged**
