### PR TITLE
remove home button

### PR DESCRIPTION
**Pull request by atao**
This button is duplicate with the title button

### CODE REVIEW

**Comment by nodiscc** [comment]
I'm ok to merge this but I'd like to have feedback from other people. Thanks for the patch @atao

**Comment by atao** [comment]
@nodiscc ok tanks! I wait feedback from other people!

**Comment by alexisju** [comment]
I'm not sure that a really good idea. Usually it is attended to find a "home" button on menu bar. It is true in most webdesign guidelines...

http://blog.evolvecreativegroup.com/post/2014/07/23/Yes-Your-Website-Still-Needs-a-Homepage-Button-or-Link.aspx

**Comment by atao** [comment]
yes but it is not an obligation to follow the standard!!

**Comment by atao** [comment]
that other people think about this idea?

**Comment by nicolasdanelon** [comment]
I'm ok with this PL :+1:

**Comment by nicolasdanelon** [comment]
the UI will be more clean

**Comment by alexisju** [comment]
If we do that, maybe we should consider improving all the default menu (the current items order is not very convenient : ie : logout as second item, rss feed on the middle,..) : 

Home Login RSS Feed Tag cloud Picture wall Daily
Home Logout Tools Add link RSS Feed Tag cloud Picture wall Daily

But i insist, a *menu* is a menu. This is not because the *title* goes to the same url as the home button it makes sense to remove.

**Comment by atao** [comment]
It's logical to click on the title button to return on the  homepage, I think

**Comment by nodiscc** [comment]
Currently we have 3 links pointing to the home page (the Shaarli logo, the title, and the Home button), that's why I'm ok with this PR. I also agree that the menu needs some improvement. Reordering it and adding symbolic icons to buttons? ("home" icon next to the title?). Other ideas welcome

**Comment by atao** [comment]
we could add an icon "home" under the shaarli logo and remove the home button

**Comment by nicolasdanelon** [comment]
just delete de home link, ok? the title... is ok... who cares? maybe the title link has some identity from the original theme.. don't know. But the home button is redundant :)

**Comment by atao** [comment]
just add a "home" icon on the title button or under the logo. what do you think?

**Comment by atao** [comment]
And delete home button

**Comment by nicolasdanelon** [comment]
I don't see the icon usefull... loock... lovely and clean
screenshot from 2015-05-12 17-47-12

**Comment by nicolasdanelon** [comment]
Hmmmm......... this is weird, dont know
screenshot from 2015-05-12 17-48-32

**Comment by atao** [comment]
I prefer without the home button...

**Comment by nodiscc** [comment]
@atao can you edit your pull request to include a home icon next to the title? It should be a symbolic, white icon IMHO.

<sup>By the way you committed directly to master, this is discouraged because you'll have trouble syncing back with the main repo. Ideally you should work on changes in separate branches, or know how to unf*ck a git history with reset --hard/checkout</sup>

**Comment by qwertygc** [comment]
:+1:  just keep the title icon and remove "home" icon.

**Comment by atao** [comment]
I don't understand what's means... IMHO... Can you explain?

**Comment by nodiscc** [comment]
"In my humble opinion"

**Comment by ArthurHoaro** [comment]
:+1: for this PR with the home icon. Can you add it @atao?

Also, while we work on it, I think the "Logout" button would be better at the end of the list.

**Comment by nicolasdanelon** [comment]
yes, logout at the end of the list please! I close my session too many times by misstake :(

**Comment by ArthurHoaro** [comment]
Closing this due to lack of feedback and templates rewriting is in progress.

**Pull request closed without merging**
