### PR TITLE
OR tag search

### LINKED ISSUE #968: OR search
Hello,
As an information studies student, I was wondering if Shaarli could (i haven't been able to make it work if so) or intend to allow boolean search. In a very large collection of bookmarks, it seems to be a very good idea to  (at least) rely on the AND, OR and NOT operator.

Also, is there a way to create some sort of reference index that would act as a relay for equivalency terms, either being synonyms (for instance, if input "arms" the search engine would also bring up "weapons") or language translation?

I don't know how much additionnal work this would add on the developper side, since I can't code myself, but i'd tend to believe it would be a major add-on to the software.

Thank you for your work,
Mathieu

### LINKED ISSUE #1797: [Feature Request] Multiple tag searching
Hello 
On my Shaarli ([here](https://liens.vincent-bonnefille.fr/)) I would like to make multiple tag searching...
A way to allow users to search searchtags="XXX" **or** "YYYY" ( || )
not searchtags="XXX" **and** "YYYY" (like actualy do) ( && )

For my use of Shaarli this conditional option will help user finding more contents (or affiliate content)

And exemple of multiple "sub-category" of tags, a situation where, mutiple tag searching can help finding all :
Capture d’écran 2021-09-06 à 12 43 33

I already remove the addtag function on clicking them...
But, here, I dont know how to add this feature

### PR DESCRIPTION
**Pull request by kcaran**
Fixes #968 
Fixes #1797

I've updated the tag search to support '~' as one or more optional search terms (i.e. OR). I also added '+' as an optional operator for AND searches. The '+' is useful for search field suggestions: '+a' will only suggest tags that start with 'a', not any tag with an 'a' anywhere in the string.

Finally, I updated the docs with the new operators. It didn't mention that asterisks ('*') can be used as wildcards, so I included that as well. 

You can try it out on my server if you wish:

https://shaarli.kcaran.com/

I hope this is helpful! I love Shaarli and would be honored to contribute.

### CODE REVIEW

**Review by ArthurHoaro — APPROVED** [review]
It looks good to me, it's working, the tests are passing, and new tests have been added.

:raised_hands:

**Comment by bonnebulle** [comment]
Works great, thanks

**Comment by bonnebulle** [comment]
Thanks, I quickly review the code (before pull)
I also try to simply clone your git with the right branch 'or-tag-search'
For now, I have a white page of death (nothing appear) 
I will retry soon (sorry, noob comment here)
Thanks for your amazing work

**Comment by ArthurHoaro** [comment]
@bonnebulle Git installation requires more steps https://shaarli.readthedocs.io/en/master/Installation/#from-sources

**Comment by raphaelbastide** [comment]
I am trying to understand how to use `~`, could you point me to an url? https://shaarli.kcaran.com/?searchterm=&searchtags=webdesign+%7Eyoutube+ is not working as `webdesign OR youtube`, right?

**Comment by kcaran** [comment]
Shaarli doesn't have operators like AND or OR in tag search. To get webdesign OR youtube you would need "~webdesign ~youtube". Here's an example with one tag each:

https://shaarli.kcaran.com/?searchterm=&searchtags=~api+~oo+

Currently, the OR operator is ignored if it isn't present on all the search terms. So "webdesign ~youtube" is equivalent to "+webdesign +youtube".

**Comment by raphaelbastide** [comment]
I see, thank you for your help! @kcaran

**Pull request merged**
