### PR TITLE
Improved search: combine AND, exact terms and exclude search.

### LINKED ISSUE #358: '-' operator for search/tags
This is a feature that I have been found missing for some time in Shaarli: negative filtering of search results.

This has multiple use cases, mostly I have some tags that are for things that I have an interest in (personal bookmarks, documentation, technical topics) and I wish friends and visitors that have no interest in this could filter them out (eg send them a mail _check what cool links I have found this week https://my.shaarli.url/?searchtags=-doc-tech-poney_). Right now the `-` operator is treated like any other character.

note that I still would like these links publicly visible, private links have a different purpose

UI for this is a separate issue; but URL params for this would be nice.

What do you think?

### LINKED ISSUE #454: Combine exact term search with AND search
To support this kind of search:

> "exact search" other terms

### PR DESCRIPTION
**Pull request by ArthurHoaro**
Handles those searches

> "exact search" term other term -notthis "very exact" stuff -notagain

Fixes #454 and fixes #358 (combined with #446).

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Update: fixes PHP 7 compatibility.

**Comment by ArthurHoaro** [comment]
Added (2nd commit): Support text search across link fields.

**Comment by nodiscc** [comment]
Added to documentation (browsing & searching)

**Comment by ArthurHoaro** [comment]
Great! Thanks.

**Pull request merged**
