### PR TITLE
Store bookmarks as PHP objects and add a service layer to retri…

### LINKED ISSUE #445: Switch to full object links DB
_Disclaimer_: this is technical.

`LinkDB` currently implements the `ArrayAccess` interface. It means that we have an object which behave like an array and works fine with our datastore file. Brilliant idea! In theory.

From [SO](http://stackoverflow.com/questions/20053269/indirect-modification-of-overloaded-element-of-splfixedarray-has-no-effect):

> When you accessing elements from <ArrayAccess object> using the [] operator it behaves not exactly like an array. Internally it's offsetGet() method is called, and will return in your case an array - but not a reference to that array.

This leads to my issue because our data structure is a multidimensional array. I encountered issues setting data in this array and, most importantly, I couldn't run some `array_*` functions. So it kinda loses its initial goal.

I think it would be better to have a `LinkDB` class which manages `Link` objects. And then only our `read/writeDB()` functions handle the object <-> array <-> file interface.

### PR DESCRIPTION
**Pull request by ArthurHoaro**
This PR includes three major changes in Shaarli internal code base:
   
   * All bookmarks are now stored as Objects instead of raw arrays
   * There is a new service layer to retrieve bookmarks, therefore datastore array shouldn't be accessed directly anymore
   * Markdown rendering have been integrated the Shaarli's core, using a dedicated formatter.

There is also two minor functional changes:

   * an empty datastore will now longer re-create the default bookmarks, they will be initialized once after a fresh install.
   * if `dev.debug` is set to true, any warning will raise an exception

The update process will work fine with the help of existing code moved to `Legacy` classes.

## Basics

All methods available to retrieve bookmarks are defined in `BookmarkServiceInterface` (e.g. get/add/set/remove/search).  
For now, there is only one service available `BookmarkFileService`, which uses the same serialized file storage in `datastore.php` as before.

This will allow us to implement services with real RDBMS such as SQLite, MySQL, etc. without touching anything in Shaarli's code base.

Internally, the service manipulates an array of Bookmark objects using `BookmarksArray` which is an `ArrayAccess` interface just as before.

Also, there is a new set of classes implementing `BookmarkFormatter` which convert Bookmark objects into arrays for templates and plugins. There is three formatters available:

   * `Raw`: just convert the object into an array without any alteration, used for example for `editlink` template
   * `Default`: default formatting, just like before without Markdown plugin enabled
   * `Markdown`: Markdown formatting

Then, in controllers, the workflow is:

   1. Use the Service to retrieve one or multiple bookmarks.
   2. Manipulate the bookmarks if necessary
   3. Call the formatter to convert into an array
   4. Call plugins hooks with links as array
   5. Render templates using the array

## Code review

I've tried to split the commit to make the code more readable:

   * the first commit only includes the introduction of the new system and moving old classes to legacy
   * the second commit contains all code base changes implementing these new features
   * the third commit is unit tests

Note: for semantics, I've tried to rename every variable related to Bookmark objects to `$bookmark` while keeping `$links` for arrays. 

## Tests

Besides unit tests, I have run quite a lot a tests to make sure I didn't break anything, but I'd like if anyone could try it before merging this.

Fixes #445

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
I would like to get this merged before working on other features. What's your opinion on this?

**Comment by virtadpt** [comment]
It would be really handy on mobile, to minimize load time and speed up ^F searching.  I worked around this use case with a bot.

**Comment by nodiscc** [comment]
> I would like to get this merged before working on other features.

Definitely. It might warrant a new release.

> What's your opinion on this?

I've read half way through the patch and it looks very good so far, but it's a large patch and I would like to do some manual testing (ie. upgrade from my current install and check if everything goes well). I'll try to report back on saturday.

**Comment by ArthurHoaro** [comment]
> I worked around this use case with a bot.

What do you mean? 

> It might warrant a new release.

I think you're right. I can release v0.11 after fixing #1331. Note that this version will contain BC with 3rd party plugins due to namespaces.

And thanks for your time!

**Comment by virtadpt** [comment]
>> I worked around this use case with a bot.
> What do you mean?

It was much more efficient to write a bot that I can talk to with XMPP, which then interacts with the API and sends back only what I need, than it was to keep interacting with my Shaarli installs with a mobile browser.  Significantly less data traffic, plus I was able to add some smarts to make searches a bit more effective.

**Comment by nodiscc** [comment]
Could a locking mechanism/concurrent access prevention be added in `BookmarkFileService`? Asking because this could be another way to fix https://github.com/shaarli/Shaarli/issues/1132, https://github.com/shaarli/Shaarli/pull/1145. (https://github.com/shaarli/Shaarli/pull/1145 is simpler though)

**Comment by ArthurHoaro** [comment]
For sure, I'll work on it when I have some time.

**Comment by ArthurHoaro** [comment]
This PR has been opened for 5 months. I will probably rebase, review and merge it when I have some time to work on Shaarli in the future weeks.

**Pull request merged**
