### PR TITLE
New plugin system

### PR DESCRIPTION
**Pull request by nodiscc**
* remove archive.org integration from main code
 * add a plugin system: 
   * add a new global variable 'PLUGINS', which is an array containing names of plugins that will be enabled.
   * plugins are RainTPL template chunks that will be injected at appropriate locations during the rendering (see next commits for examples).
   * build a list of plugins for each location (footer, toolbar, linklist) based on the `PLUGINS` array, and if the corresponding template chunk exists.
   * at each location, loop over the enabled (and existing) plugins, and include them using RainTPL `include=`.
   * Misc: move rendering the linklist to a separate function.
   * Misc: create a `PageBuilder` **every time** we render the page. This is not always needed, , it now allows us to setup global page settings, like we'll do with plugins.
   * Credits to @pikzen for finding a way to build proper plugin lists for each location (and not needing blank templates to prevent RainTPL from crashing...)
 * cleanup: compute `shorturl` (`linkdate|smallHash`) only once
 * move QR code to a plugin
   * move RainTPL template chunks for QR code rendering to `tpl/plugins/qrcode`
   * move required resources (js, image) there and update COPYING
   * use the minified qr.js
   * enable the `'qrcode'` plugin by default in `index.php` `'PLUGINS'` config array
 * move archive.org integration to a plugin …
   * Disabled by default; to enable it, add `'archiveorg'` to the `'PLUGINS'` config array in `index.php` or `data/options.php`
 * add "playvideos" plugin: adds a "Play videos" toolbar button …
   * code from https://github.com/zaius/youtube_playlist/
   * Plays all Youtube videos linked from the page in an overlay HTML5 player
   * See it's README.md
 * plugin system: allow adding elements to the page `<head>` `(tpl/plugins/*/*.includes.html)`

### CODE REVIEW

**Comment by nodiscc** [comment]
Working on 2 more plugins: https://github.com/nodiscc/Shaarli/tree/wallabag-plugin https://github.com/nodiscc/Shaarli/tree/readityourself-plugin. These will allow storing plugin settings in an `options.php` file directly in the plugin directory.

We may want to move the link description field rendering to a plugin. This kleaves room to custom renderers (markdown parser was requested).

Comments welcome.

**Comment by e2jk** [comment]
In your last post you indicate about the other 2 plugins that "These will allow storing plugin settings in an options.php file directly in the plugin directory."
This will make it more difficult/need to path for the [Debian] package. Wouldn't it be possible to have all options (plugin and core) in the same settings file?

**Comment by e2jk** [comment]
Regarding the pull request itself, I currently don't have the bandwith nor the mental space to review this large number of changes. Can somebody else review it? I'm trusting your judgment for merging.

**Comment by nodiscc** [comment]
It's easier to review commit by commit; let me know if there's something you want explained.

**Comment by nodiscc** [comment]
I added the wallabag sharing plugin and changed my mind: all options (including plugin options) need to be defined in either `index.php` or `data/options.php`. @e2jk I hope you can see the shortcomings now. We are providing defaults directly in index.php for optional plugins.

If we remove the defaults from there means the plugin _will not work_ until the user

1. Enables the plugin in `data/options.php`
2. Manually copies the relevant option (here `WALLABAG_URL`) from the plugin's README, and sets it to his own customized value. A lot of manual changes.

I'd like to propose something better, but as you want to keep everything in the same config file, this is what I have.

**Comment by nodiscc** [comment]
add readityourself plugin, requested at sebsauvage#66 …

This plugin adds, for each link, a button to display a more readable version using an external
readityourself service (self-hostable, https://github.com/memiks/readityourself)

**Comment by nodiscc** [comment]
made readityourself plugin base url configurable throught the `READITYOURSELF_URL` config variable

**Comment by nodiscc** [comment]
All right I'll close this pull request. I pushed the plugin system to the branch https://github.com/shaarli/Shaarli/tree/new-plugin-system in this repository so that everyone can work on it. Continuing discussion at https://github.com/shaarli/Shaarli/issues/14

**Pull request closed without merging**
