### PR TITLE
Fix issue 366, Problem when shaaring a link in Reader View of Firefox

### PR DESCRIPTION
**Pull request by StyMaar**
Unfortunately, the diff if pretty ugly because this affects the bookmarklet.

### CODE REVIEW

**Comment by nodiscc** [comment]
Wouldn't it be simpler to sanitize the `about://reader?url=` out of stored URLs? (like we do with `annoyingQueryParams`) Instead of cluttering the bookmarklet for a browser-specific feature.

**Comment by virtualtam** [comment]
Hi all!
A more elegant solution would be to move the bookmarklet(s) as plugin(s) once the [Plugin System](https://github.com/shaarli/Shaarli/wiki/Plugin-System) (#275) is merged - this would enable users to easily define and manage custom bookmarklets that suit their environment best :)

**Comment by StyMaar** [comment]
@nodiscc you're probably right. Editing the bookmarklet was an easy work-around the problem without deploying a new version of shaarli on my server, but handling in directly in the backend makes more sense I think.

@virtualtam I don't think so for two reasons:
- the bookmarklet is really a core feature of shaarli, and as so it shouldn't be an opt-in plugin.
- A bookmarklet is easily customizable by definition: one just need to edit the JavaScript directly in his browser if he has specific requirements. (that's what I did in this case, even though I decided to report the bug upstream)

**Comment by nodiscc** [comment]
Adding this workaround to the wiki is another option (https://github.com/shaarli/Shaarli/wiki/Troubleshooting)

**Comment by ArthurHoaro** [comment]
About the plugin, I agree with @StyMaar, having a bookmarklet shouldn't be a plugin, plus it's a core feature widely used (or so I think). Having additional bookmarklet as plugins, such as #143, isn't a problem though.

Removing the `reader` part with the `Url` class as suggested by @nodiscc is doable. But it will need a bit of work since `$annoyingQueryParams` is used to clean up the `query` part of the URL.

While not super elegant, this PR is working fine, I'm ok for merging it.

**Comment by StyMaar** [comment]
@ArthurHoaro I started working on @nodiscc suggestion yesterday. I may come back with a new pull request in a few days (most likely this week-end). No need to merge this inelegant quick-fix.

**Pull request closed without merging**
