### PR TITLE
Theme improvements: move thumbnails to the right and reduce margins overall

### PR DESCRIPTION
**Pull request by ArthurHoaro**
* Reduce multiple margins (markdown, space between block, etc.)
  * Move thumbnails to the right in the same line as the title
  * Move edit button as floating to the left
  * Move fold/collapse and checkbox buttons as floating to the right
  * Add a bunch of HTML ID in the linklist template

Relates to #877

shaarli-thumb

### CODE REVIEW

**Comment by virtualtam** [comment]
It feels weird having the controls (edit, delete, select, collapse) all over the place, and out of the link area; what about adding a designated area for controls, e.g. on the left of a link's description?

```
------------------------------------- 
| LINK TITLE                    | ^ |
-------------------------------------
| C | Description        | THUMB    |
| T |                    |          |
| R |                    -----------|
| L |                               |
-------------------------------------
| LINK META                         |
-------------------------------------
```

```
------------------------------------- 
| LINK TITLE                    | ^ |
-------------------------------------
|     Description        | THUMB    |
|                        |          |
|                        -----------|
|                                   |
-------------------------------------
| CTRL | LINK META                  |
-------------------------------------

Press any key to continue...
```

**Comment by nodiscc** [comment]
I don't see a problem with controls outside the link area, but they should definitely be in the same place :) Bottom right or bottom left in the link metadata area would be nice.

_PS @virtualtam what do you use for ASCII drawings? I've been looking for a good FOSS ASCII drawing app for some time_

**Comment by virtualtam** [comment]
@nodiscc mostly emacs/vim ^_^

I'd recommend PlantUML's [ASCII render](http://plantuml.com/ascii-art) for more complex stuff though; more ideas:
- https://unix.stackexchange.com/questions/126630/creating-diagrams-in-ascii
- http://search.cpan.org/dist/App-Asciio/lib/App/Asciio.pm

**Comment by ArthurHoaro** [comment]
@virtualtam 
I've tried multiple placements before this one. The main goal here is to reduce the white space generated by links containing only a thumbnail, thus put it on the title line and move top right buttons.

I can group edit and delete buttons to reduce the impression of having controls all over the place.

Your first suggestion isn't ideal because controls then create a lot of white space in empty links, and create a left margin which feels a bit odd for the other ones. I'll try the second one. But...

tl5za8a

@nodiscc Thanks!

**Comment by ArthurHoaro** [comment]
New suggestion:
shaarli-controls

**Comment by virtualtam** [comment]
> New suggestion

Nice!

I guess what was bothering me was having UI components out of the link area (div).

I'm not sure where would be the best place to put the collapse/expand button though; it should at least be kept vertically aligned with the top and bottom collapse/expand buttons to keep the UI coherent. Maybe it could go to the right of the bookmark URL on the bottom right?

I'd also suggest visually separating the control buttons from the link metadata, maybe by using a slightly different background color, or a vertical separator.

**Comment by ArthurHoaro** [comment]
Thanks for the review. Updated with fold button next to the URL on the bottom right, and a vertical bar next to the buttons on the left.

**Pull request merged**
