### PR TITLE
Fixes #494: inputs & labels with plugin name

### LINKED ISSUE #494: Plugin admin plugin name
Can we add a `str_replace("_", " ", $key);` in `$key` variables (file: tpl/pluginsadmin.html) in order to see a better or more readable information
Or maybe add a new line in *.meta file (:

### PR DESCRIPTION
**Pull request by nicolasdanelon**
#494

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
It looks good, thanks! :+1:

**Comment by nicolasdanelon** [comment]
Arthur I know it but the code is validated at https://validator.w3.org/#validate-by-input

**Comment by ArthurHoaro** [comment]
Yes that what I meant by correct.

**Comment by nicolasdanelon** [comment]
Oh, I'm sorry ! I didn't read your complete message! hahaha

**Pull request merged**
