### PR TITLE
SVG logo, cleaned.

### PR DESCRIPTION
**Pull request by mro**
maybe using on readme isn't a good idea. 

But having it in the repo may be. 

Did separate commits by intention.

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Nice! You went through a lot of French to find that!

While it's nice to have it (because it's vectorial), the file is more than 3x larger. We probably keep displaying the PNG. Also your file shouldn't be executable.

**Comment by ArthurHoaro** [comment]
Oh, that probably doesn't gonna work anyway because I think that the `doc/` folder is generated from the wiki.

ping @virtualtam

**Comment by virtualtam** [comment]
Yup, the `doc` folder is reset each time the local documentation is re-generated from GH wiki; to be usable from the doc, it'd need to be versioned under the `Shaarli.wiki` repository, which I think should be clone-able as well as push-able to from any GH account, as it is publicly editable from the web interface.

On the long-term it'd be good to have the doc and the code share the same repository (#312), so all static resources are bound to show up in the main repo.

**Comment by nodiscc** [comment]
@mro clone the wiki with `git clone https://github.com/shaarli/Shaarli.wiki.git`, copy the SVG there, `git add; git commit; git push` it.

**Comment by mro** [comment]
Lol, is there documentation required on how to contribute to documentation?

Sagt das Perpetuum Mobile.

**Comment by nodiscc** [comment]
All the doc lives in the wiki. The doc/ directory is just copied there. It allows anyone to edit the doc without having to go through Pull Requests.

**Comment by ArthurHoaro** [comment]
Just to clarify: any Github wiki is a git repo available under `https://github.com/<user>/<repo>.wiki.git`.

**Comment by mro** [comment]
>  https://github.com/shaarli/Shaarli/pull/482#issuecomment-185175923 the file is more than 3x larger.

If you're concerned about size, save it as `.svgz`, et voilá, it's 25% smaller than the `.png` :-)

**Pull request closed without merging**
