### PR TITLE
Feature: bulk creation of bookmarks 

### LINKED ISSUE #137: batch "add multiple links" feature
When we use one browser's window per topic search, it could be handy to save all the tabs in that window with the same tags in shaarli (like Command + Shift + D in Chrome osx version e.g.)

Of course , and as it hsas been said in others issues, copy/paste tags is possible for each tab we want to bookmark, but I found that way quite overkill.

### PR DESCRIPTION
**Pull request by ArthurHoaro**
This changes creates a new form in addlink page allowing to create
multiple bookmarks at once more easily. It focuses on re-using as much
existing code and template component as  possible.

These changes includes:
  - a new form in addlink (hidden behind a button by default),
containing a text area for URL, and tags/private status to apply to
created links
  - this form displays a new template called editlink.batch, itself
including editlink template multiple times
  - User interation in this new templates are handle by a new JS script
(shaare-batch.js) making AJAX requests, and therefore does not need page
reloading
  - ManageShaareController has been split into 3 distinct controllers:
    + ShaareAdd: displays addlink template
    + ShaareManage: various operation applied on existing shaares
(change visibility, pin, deletion, etc.)
    + ShaarePublish: handles creation/edit forms and saving Shaare's
form
  - Updated translations

Fixes #137

--------
The PR is currently in progress because it relies on async retrieval of metadata (#1567 and #1584), but I encourage you to test it and provide any feedback you'd have, especially regarding the UI/UX.

You can find a live demo here: https://shaarli-batch.hoa.ro (demo/demo)

### CODE REVIEW

**Comment by gruenheit** [comment]
The bulk creation uses the configuration setting "Private links by default > All new links are private by default" even if one decides to toggle the "private" setting to public, it is re-activated with every single step = twice, so this is very annoying!

Shaarli_Next_new_feature_bulk-links_20201010_201333

**Comment by ArthurHoaro** [comment]
Good catch! Thanks for the report, I'll try to fix that tomorrow.

**Comment by leNEKO** [comment]
Salut Arthur :)

Nice feature, but maybe it would need some UI feedback when dealing with `save all` on a big list (a screencast https://webm.red/view/Pc6x.webm)

**Comment by ArthurHoaro** [comment]
Merci Nico ! =)

You are right, it's very obvious with a large batch of URLs like shown on your screencast.
I have added a progress bar in the middle of the page, with a darkened background to give some feedback to the user. I have also reduced the loading time by memoizing tag list retrieval.

Note that while it works, my web server (or the social media where we extract metadata) doesn't very much like being hit by 60x2 HTTP requests from the same client a few seconds apart, and I have encountered a time out once.

For large batches I'd recommend using our [Python client](https://github.com/shaarli/python-shaarli-client) + REST API, or the import/export format.

**Pull request merged**
