### PR TITLE
Add a filter to only display public links

### LINKED ISSUE #1030: Ability to filter out/hide private links
I use Shaarli with `hide_public_links` and `force_login` both set to true, so my entire set of links requires authentication. I mark personal links as "private" and leave professional stuff unmarked. It would be excellent if I could choose to have private links filtered _out_ by default in listings and searches (even when searching myself) and use something like the current "filter private links" button to choose to show them.

I think this would be a new feature, unless I'm missing some existing way to do this with hidden tags.

### PR DESCRIPTION
**Pull request by ArthurHoaro**
When the key filter is clicked once, it only displays private link. When it is clicked on again, it becomes red and only public links are displayed. Another click and all links are displayed. The current visibility status is shown in the search banner

Fixes #1030

### CODE REVIEW

**Comment by virtualtam** [comment]
In terms of accessibility, I'm not too fond of using more than two states for a toggleable visual element...

Maybe we could replace/augment the clickable key icon with a drop-down _Visibility_ menu featuring the following entries:
- all (default)
- public (default when the user chooses to hide private links)
- private

**Comment by ArthurHoaro** [comment]
You're right, I'll try to do something like that.

**Comment by ArthurHoaro** [comment]
PureCSS doesn't really provide drop down feature, and making dropdown menu in CSS brings me nightmare from 10 years ago. Do you think it would be acceptable to have 3 distinct buttons: All/Private/Public, with an icon associated to each one?

**Comment by nodiscc** [comment]
> Or maybe only two of them, only private/only public, and re-toggling them would display all links?

I think this is the best solution. The two private-only/public-only filters would be mutually exclusive. Toggling one on disables the other. Toggling the active one, would disable it. The `search-result-block` below also explains the current filter state in plain words (`n results with status {private,public}`).

Mockup of possible states (notice I changed the icon, that's what made sense to me)

mkp-shaarli-filter

**Comment by virtualtam** [comment]
+1 for using several buttons

The following icons from Font Awesome might also be suitable:
- http://fontawesome.io/icon/user/
- http://fontawesome.io/icon/users/
- http://fontawesome.io/icon/globe/
- http://fontawesome.io/icon/user-secret/

**Comment by ArthurHoaro** [comment]
Thanks for the feedback. PR updated. I have used `user-secret` + `globe`, but the locks were fine too. Let me know if you want to me to change.

**Comment by HappyDino** [comment]
Hi all,
I'm very interrested by this feature.
How can I install it ? I'm on lastest release v0.9.5.
Sorry if it's a dumb question, I'm beginning on git.

**Comment by ArthurHoaro** [comment]
Hi, this feature has been merge in the development branch, but hasn't been released yet. You will have to wait for the `v0.10.0` release, or install the [development version](https://shaarli.readthedocs.io/en/master/Download-and-Installation/#development-version-mainline).

**Comment by HappyDino** [comment]
Thanks a lot for this quick answer.

**Pull request merged**
