### PR TITLE
Add a target to generate Doxygen documentation 

### PR DESCRIPTION
**Pull request by virtualtam**
_Note: I've split this PR in two commits, this way, Doxyfile customizations for PHP/Shaarli are easier to read_

Relates to #95

Customizations for PHP/Shaarli:
 - add project information
 - index PHP files
 - index global functions
 - exclude directories

Usage
[EDIT] Install `doxygen` from your distro's package repositories.

```bash
 $ make doxygen
 $ firefox doxygen/index.html &
```

Notes
 - classes can be found under "Data Structures"
 - global functions can be found under "Files > Globals > Functions"

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
```
$ make doxygen
Suppression de composer.phar
make: doxygen : commande introuvable
Makefile:121 : la recette pour la cible « doxygen » a échouée
make: *** [doxygen] Erreur 127
```

Do I need to install something?

**Comment by virtualtam** [comment]
> Do I need to install something?

Yup, description updated! Any version of `doxygen` from your distro's repositories should do the trick; the latest versions (> 1.8) enable Markdown support, though.

> EDIT: also, the clean goal is a bit annoying.

It is necessary there, not to index temporary/ backup files. It may be annoying if you have installed stuff locally (eg Composer), but this can easily be avoided by putting executables somewhere in a custom PATH :p

**Comment by ArthurHoaro** [comment]
Thank you. It works fine when there are docstrings.

Any particular reason for the uppercase D in Doxyfile?

**Comment by virtualtam** [comment]
Nope, it's just a convention, similar to a `CMakeLists.txt` file for CMake builds, for example. The file could perfectly be located under an other directory, with another name, etc.

**Comment by nicolasdanelon** [comment]
should this be only for developers?

**Comment by virtualtam** [comment]
It's mostly useful for:
- developers who want to get info about the code (API, method signature, documentation...) without necessarily delving into it
- online source browsing, e.g. to avoid cloning repositories and creating IDE projects
- see how well your code is documented

**Comment by virtualtam** [comment]
Bump :)

If there's no objection, I'd like to merge this PR to help in refactoring tasks (#324, #372)

**Comment by ArthurHoaro** [comment]
Go ahead. :)

**Comment by virtualtam** [comment]
Thanks!

**Pull request merged**
