### PR TITLE
Add Yunohost install badge in the ReadMe

### PR DESCRIPTION
**Pull request by lapineige**
Proposal : Add a button to install with Yunohost in a one-click way.
This would reference the existence of an easy/user-friendly install for Yunohost users.

Note: this is just a proposal, feel free to change the way I integrated the button / message in your ReadMe (I'm wondering for instance why there is no "How to install" part, and if this addition would not confuse people: they could think Shaarli can only be installed with Yunohost)

### CODE REVIEW

**Comment by virtualtam** [comment]
Thanks @lapineige for reaching out!

Given this is a third-party integration (i.e. not directly maintained by the Shaarli community), the Yunohost deployment option would best fit under a section of the [HTML documentation](https://shaarli.readthedocs.io/en/master/)

**Comment by lapineige** [comment]
Ok, in which part of the doc would you like me to integrate this ? Home, Setup ?

**Comment by nodiscc** [comment]
@lapineige I think the best place would be https://github.com/shaarli/Shaarli/blob/master/doc/md/Community-%26-Related-software.md#integration-with-other-platforms

**Comment by virtualtam** [comment]
Closing as superseded by #1164

**Pull request closed without merging**
