### PR TITLE
improve display in pluginadmin

### PR DESCRIPTION
**Pull request by agentcobra**
I have done some code this evening.

### CODE REVIEW

**Comment by agentcobra** [comment]
This is a screenshot of changes :
image

**Comment by agentcobra** [comment]
It's one solution for #945

**Comment by nodiscc** [comment]
@agentcobra any updates? Are you still working on this?

**Comment by agentcobra** [comment]
@nodiscc thé code is working well.
I just searched a solution to have a better plugging panel

**Comment by agentcobra** [comment]
maybe later

**Pull request closed without merging**
