### PR TITLE
Adding 3rd party plugin 'markdown-toolbar' to docs

### PR DESCRIPTION
**Pull request by immanuelfodor**
Hi Everyone,

I spent the last couple of days creating a markdown editor plugin to Shaarli, if you think it is helpful for others, we can include it in the documentation. This plugin is a lot more complex thing than PR #1042, but I think it well worth the effort. It improved the overall link adding/editing experience a lot for me, especially on mobile. It was a pain every time to get the symbols on my Android keyboard, but now it is a single click.

https://github.com/immanuelfodor/shaarli-markdown-toolbar

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Thanks, however your plugin doesn't seem to work with the default template, so it should be specified that it requires the Material theme.

**Comment by immanuelfodor** [comment]
What do you mean by doesn't seem to work? I tested it on the default and also made some minor CSS changes regarding to that theme to fully support it, not just the material.

default-theme

**Comment by ArthurHoaro** [comment]
Issue opened here: immanuelfodor/shaarli-markdown-toolbar#1

**Comment by immanuelfodor** [comment]
Issue solved at  immanuelfodor/shaarli-markdown-toolbar#1 in 0bf68dd.

**Pull request merged**
