### PR TITLE
Add a .gitattributes to ease repository management

### PR DESCRIPTION
**Pull request by virtualtam**
TL;DR: let Git cleverly handle line endings and diffs, tidy release archives a bit ;-)

Features:
- enforce LF (Unix) line endings
- omit dev/test resources & code from Git(Hub) archives
- treat minified resources (CSS, JS) as binaries to avoid cluttered diffs

Resources:
- http://git-scm.com/docs/gitattributes
- https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes
- https://help.github.com/articles/dealing-with-line-endings/
- http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/
- https://github.com/Danimoth/gitattributes

### CODE REVIEW

**Comment by nodiscc** [comment]
Thank you :+1: the provided links are a good read.

**Comment by virtualtam** [comment]
You're welcome ;-)

Not sure if trailing spaces should be handled as well, for now I only stumbled upon user-defined scripts that can be called as filters (thus acting as pre-commit hooks). Maybe for a further commit.

I also hesitated to add Composer configuration to archive-excluded files, as it _could_ come handy if we use it to update PHP deps (similarly, [Bower](http://bower.io/) could be introduced to handle JS/CSS libs). AFAIK those can be excluded until we decide to use them for more than unit-testing :)

**Comment by virtualtam** [comment]
Also excluded from archives:
- Composer config;
- documentation (GitHub wiki) sources;
- Git config;
- Travis config.

**Comment by ArthurHoaro** [comment]
I didn't know we could do that. Great!

**Pull request merged**
