### PR TITLE
Plugin page targets: preserve backward compatibility

### PR DESCRIPTION
**Pull request by ArthurHoaro**
A few legacy routes defined here do not match the template file name,
and require tweaking stuff during the rendering for plugin target definition.

Instead we define a mapping to preserve backward compatibility for plugins

ping @immanuelfodor

### CODE REVIEW

**Review by immanuelfodor — CHANGES_REQUESTED** [review]
I could alsouse the following if statement:

```php
if (in_array($data['_PAGE_'], [ $router::LEGACY_TARGET_MAPPING[$data['_PAGE_']], $router::$PAGE_EDITLINK) ] ) {
...
```

But this starts to become convoluted and doesn't solve the old router not having the map. I feel we need a better way of determining which Shaarli are we running in. Maybe we need two if-s to first determine the Shaarli version and then the necessary comparison for the route:

```php
if (is_new_shaarli_magic_function() && $router::LEGACY_TARGET_MAPPING[$data['_PAGE_']] == $router::$PAGE_EDITLINK)  {
...
}
if (!is_new_shaarli_magic_function() && $data['_PAGE_'] == $router::$PAGE_EDITLINK) {
...
}
```

But this leads to duplicated business logic inside the if-s, and also could result in 2^n if-s if I also need the else statements (which is not true: I'm in an X shaarli version or not on the required page). 

I really want to approve this PR but I can't see how it "preserve backward compatibility" (from the title). :(

**Comment by ArthurHoaro** [comment]
I think you misunderstood what I tried to do here. I added and used `LegacyRouter::LEGACY_TARGET_MAPPING` in order keep the same value sent to plugins between v0.11 and v0.12 (here `edit_link` instead of `editlink`). It is not necessarily supposed to be used directly by plugins.

So in your case you'll simply have to do

```php
if($data['_PAGE_'] === $router::$PAGE_EDITLINK) {}
```

**Comment by immanuelfodor** [comment]
Hmm, so the `$router::$PAGE_EDITLINK` will automatically contain the new `editlink` string in the legacy router?

**Comment by ArthurHoaro** [comment]
No. Before `v0.12-beta` we send `Router::$PAGE_EDITLINK` (=`edit_link`) as value to plugins in `_PAGE_` while rendering the template. I made an inconsistent change, now controllers use a helper function to call plugin hooks, based on `TemplatePage::EDITLINK` (=`editlink` value).

What changes in this PR, is that I made sure that the new helper function continues to send consistent values with previous versions. In your case, it sends to plugins `LegacyRouter::LEGACY_TARGET_MAPPING['editlink']` (=`edit_link`). In other words, `_VALUE_` won't change between previous and next versions.

**Comment by immanuelfodor** [comment]
| Version | Router class (in `$router`) | `$data['_PAGE_']` value | `$router::$PAGE_EDITLINK` value | `$data['_PAGE_'] === $router::$PAGE_EDITLINK` | `$router::$LEGACY_TARGET_MAPPING` exists?  | `$router::$LEGACY_TARGET_MAPPING[$data['_PAGE_']] == $router::$PAGE_EDITLINK`
| ---------- | ------------------------ | ------------------------ | ------------------------ | ------------------------ | ------------------------ | ------------------------ |
| New Shaarli | `Shaarli\Legacy\LegacyRouter` | `editlink` | `edit_link` | `false` | Yes | `true` |
| Old Shaarli | `Shaarli\Router` | `edit_link` | `edit_link` | `true` | No | Error, no such static map |

My problem is that I can't see a way that plugin authors can construct a single `if` by using `LEGACY_TARGET_MAPPING` that is compatible with both old and new Shaarlies.

I think one solution could be if **new** Shaarli would set the `$data['_PAGE_']` to the new mapped value transparently when the plugin uses `LegacyRouter` (just as in https://github.com/shaarli/Shaarli/pull/1537/files?file-filters%5B%5D=#diff-421747dcbd976f5b0ec058ab31bbfb95R102), so `$data['_PAGE_'] === $router::$PAGE_EDITLINK` would be always true on both old and new Shaarlies. But how could Shaarli core know if a plugin is using which router class? It could be hard to determine if the plugin chooses the router class dynamically, just as in my case. Maybe the plugin's init function could contain a request for letting know Shaarli if it requests the mapping or not.

Second (easier) solution would be to modify the `LegacyRouter` keys to follow-up the changes in the new values. If plugin authors use `$router::$PAGE_EDITLINK`, they should not care which value it represents, so it could be the new `editlink` to make the `$data['_PAGE_'] === $router::$PAGE_EDITLINK` condition true.

**Comment by ArthurHoaro** [comment]
I'm sorry I might be missing something very obvious, or made a mistake in my PR but

> I think one solution could be if new Shaarli would set the $data['_PAGE_'] to the new mapped value transparently when the plugin uses LegacyRouter (just as in #1537 (files)), so $data['_PAGE_'] === $router::$PAGE_EDITLINK would be always true on both old and new Shaarlies.

That's exactly what this PR does. In your table, column `$data['_PAGE_']` should now be `edit_link` in both rows.

> But how could Shaarli core know if a plugin is using which router class?

It doesn't matter because the value passed is the same in the end.

**Comment by immanuelfodor** [comment]
While this PR keeps backwards compatibility, I think it breaks new plugins that only target Shaarli 0.12 =< . The example is one of the upgraded plugins. Here you're using the new method to determine the routes: https://github.com/shaarli/Shaarli/blob/master/plugins/qrcode/qrcode.php#L44 However, the `TemplatePage::LINKLIST` is `editlink`: https://github.com/shaarli/Shaarli/blob/master/application/render/TemplatePage.php#L16 So if this PR is always mapping the new routes for the old ones, how will this `if` work? It's if will never be true as `$data['_PAGE_']` will be `edit_link`. I can't see any logic in this PR to determine if the mapping is needed in the plugin or not. 

> But how could Shaarli core know if a plugin is using which router class? It could be hard to determine if the plugin chooses the router class dynamically, just as in my case. Maybe the plugin's init function could contain a request for letting know Shaarli if it requests the mapping or not.

**Comment by immanuelfodor** [comment]
In other words, the following equations should always equal to `true` (router class value in brackets)
- `$data['_PAGE_'] == Router::PAGE_EDITLINK` (edit_link)
- `$data['_PAGE_'] == LegacyRouter::PAGE_EDITLINK` (edit_link) - above two simplified as `$router::PAGE_EDITLINK`
- `$data['_PAGE_'] == TemplatePage::EDIT_LINK` (editlink)

My feeling is that it's not possible without further logic to solve this with just a simple `LegacyRouter::LEGACY_TARGET_MAPPING[$template] ?? $template` condition. You can't depend on the existence of `LEGACY_TARGET_MAPPING` as it will also exist besides `TemplatePage` so you will make the replacement even if the plugin uses the new method. But if you're not doing any replacement on `$data['_PAGE_']` value, it will break the two `$router::PAGE_EDITLINK` equations.

**Comment by ArthurHoaro** [comment]
OK, third explanation, third coffee, I got you! :smile: 
Since `TemplatePage` is now the recommended way to map the template, and `LegacyRouter` is deprecated, it does not make sense to rely only on LegacyRouter value for new plugins. That's a valid point.

> But how could Shaarli core know if a plugin is using which router class?

You're right, it'll be difficult to achieve, and hacky at best. 
I like you other solution though.

> Second (easier) solution would be to modify the LegacyRouter keys to follow-up the changes in the new values. If plugin authors use $router::$PAGE_EDITLINK, they should not care which value it represents, so it could be the new editlink to make the $data['_PAGE_'] === $router::$PAGE_EDITLINK condition true.

It changes the value, but it's not an important change, especially because it is not used elsewhere. 
And, last but not least, it doesn't require any code!

**Comment by immanuelfodor** [comment]
> It changes the value, but it's not an important change, especially because it is not used elsewhere.
> And, last but not least, it doesn't require any code!

Yes, I think this could solve this issue without touching the data page :)

**Review by immanuelfodor — APPROVED** [review]
LGTM, when the test passes, I think it's ready to merge :) I'll modify my plugins accordingly probably at the weekend.

**Comment by ArthurHoaro** [comment]
Thanks for your time and your review!

(the same build appears twice on Github with different statuses but [it's passing](https://travis-ci.com/github/shaarli/Shaarli/builds/182557382)).

**Pull request merged**
