### PR TITLE
json_encode removed

### PR DESCRIPTION
**Pull request by nicolasdanelon**
cleanup: remove json_encode() (built-in since PHP 5.2)
See http://php.net/manual/en/function.json-encode.php

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Never saw that! :-o

**Comment by nicolasdanelon** [comment]
hmmmm yeah.. it's a lot of code in that file, I don't understand everything... It's like a super model mixed with a controller, right? ahaha. I've try to create a Auth class.. but not success :/

**Comment by virtualtam** [comment]
Thanks!
Could you update the commit message to:
```
cleanup: remove json_encode() (built-in since PHP 5.2)

See http://php.net/manual/en/function.json-encode.php
````
?

**Comment by nicolasdanelon** [comment]
done, I think

**Comment by ArthurHoaro** [comment]
```
git commit --amend
git push <remote> patch-1 --force
```

**Pull request merged**
