### PR TITLE
Fixes shaarli/Shaarli#46: allow 'javascript:' links sharing

### PR DESCRIPTION
**Pull request by ArthurHoaro**
Because it's easy, and it's working.

EDIT: also, it's in 0.9 milestone.

### CODE REVIEW

**Comment by e2jk** [comment]
What kind of usecase would this serve? Do you have an example?

**Comment by ArthurHoaro** [comment]
Sharing a bookmarklet as a link. 
-- 
Arthur Hoaro

**Comment by e2jk** [comment]
I'm just wondering if this wouldn't open Shaarli to vulnerabilities (e.g. XSS). It would have to be entered by the user, but it's the same old question, should we allow the user to shoot themselves in the foot if they do unsafe copy/paste?

**Comment by ArthurHoaro** [comment]
That's a legitimate question. I'd say we should let users do whatever they want to do, but other contributor's opinion would be nice.

**Comment by nodiscc** [comment]
Bookmarklets always open a small way for XSS, like the one presented at http://www.stealmylogin.com/ (scroll down for the bookmarklet). However running a bookmarklet from your Shaarli links _is no different_ than running it from your browser toolbar.

Basically when you're running "links" that run javascript code from your Shaarli OR your browser toolbar, you have to trust the code.

This is also easily mitigated by the [`X-Content-Security-Policy`](http://content-security-policy.com/) header, (eg. the _Steal my Login_ attack doesn't work on my server) which most browsers respect.

I think we should allow users to store bookmarklets as Shaarli links. The risk is more for visitors clicking on an untrusted link, or adding it to their bookmarks bar. Anyway this is a risk even from a simple HTML page.

<sub>[RequestPolicy](https://requestpolicycontinued.github.io/) is also a good way to prevent XSS/CSRF on sites that are improperly secured</sub>

**Comment by e2jk** [comment]
> The risk is more for visitors clicking on an untrusted link

Yes, that's what I'm worried about.
What about this suggestion: You can add `javascript:` links to your Shaarli, you can click on it as much as you want when you are logged in (i.e. the person who added the link is responsible for what he puts in there), but if a non-logged-in user is clicking on such a link, we show a warning/popup/whatever that requires the user to click "Yes, please run this JavaScript code". A bit similar to how the browsers will show you a warning page if you're accessing a self-signed HTTPS site, but provide a way to go further if you know what you want.

In other words, when not logged in, the JS code is wrapped in a bit of code that will ask for confirmation.

**Comment by pikzen** [comment]
Agreed with e2jk. A nice advantage of that is that this popup can actually be implemented as a Javascript event handler on all javascript: links instead of adding it in Shaarli core.

**Comment by nodiscc** [comment]
/me scratches head

I fail to see an attack vector here. The logged-in admin/user is responsible for what links he puts on his shaarli. A social engineering attack could trick him into _"manually add this link to your shaarli to see this awesome video! you won't believe what happens next!"_, but this is no different than having him put the script in the `<head>` where non-logged in users will run the script without even knowing. Even then, the potential security impact for non-logged in users is null (there is no private data to leak, is there?)

Not saying what @e2jk proposed shouldn't be implemented. But _is it better than what we have_ -> _yes_

I'd like to merge it (storing bookmarklets is a long-wanted item). I'm not opposed to a confirmation dialog in a later PR.

**Comment by pikzen** [comment]
>but this is no different than having him put the script in the <head> where non-logged in users will run the script without even knowing.

I'd argue that users that would eventually insert an XSS through sharing a bookmarklet would hardly be able to edit the head :)

I'm not opposed to merging, a later PR is probably the best idea.

inb4 jvoisin thinks that it is a security risk :trollface:

**Comment by e2jk** [comment]
[Worth reading](http://www.hunlock.com/blogs/Bookmarklets_--_The_Evil_Lurking_In_Your_Browser). This quote somehow hurt my soul (ah, IE...), but I think there's truth in there:

>  I think IE7 has the right idea... Just a nice polite warning saying "Are you really, really sure you want to bookmark this javascript, it's quite dangerous you know". Firefox's no-questions-asked approach is convenient but sooner or later someone is going to start using bookmarklets for evil if they haven't already, and while a warning prompt isn't a panacea but it does make the user think for a second about what he or she is doing and gives them the chance to reconsider. 

Again, my suggestion is to allow bookmarklets to just work whenever you are logged in, but if you are just a visitor browsing somebody else (who might not necessarily be evil, but just didn't realize the power of what he added to his Shaarli) we provide a tiny little bit of extra security to that passer-by. Obviously, if the Shaarli admin is evil he might disable that piece of code in Shaarli, but maybe he never tested while being logged off, so who knows...

I would not want this PR merged before we finish this discussion, and ideally before this sort of guardrail is implemented. This is a new feature that wasn't yet in Shaarli after all, so it can wait a bit. If you are really in a hurry, you can still take these changes and manually apply it to your instance ;)

**Comment by nodiscc** [comment]
No hurry :) Of course this can wait until we find an agreement. While we can add a warning dialog when visitors click on the link from Shaarli, we can't warn them when they drag the bookmarklet to their browser toolbar (where the real risk lies, as described in the article) because there's no way to detect that event from Shaarli. It can be argued that when the JS link is on the Shaarli page, it is _not a bookmarklet_ but a mere link with few/no security implications.

_OT: actually IE did the right thing. Sad to see that Mozilla didn't bother to implement such a safeguard against malicious bookmarklets. Instead they chose to [completely block bookmarklets](https://bugzilla.mozilla.org/show_bug.cgi?id=866522) with no workaround when the site's CSP forbids them._

I'd like to have other opinions too.

**Comment by e2jk** [comment]
Let's not mix 2 topics: I am not talking, nor concerned about the Shaarli bookmarklet that people drag from Shaarli to their bar. I am slightly (note: I'm not losing sleep over this issue ;) ) worried about random JavaScript code that somebody on the Internet adds to their Shaarli, and another visitor finds the name of the link interesting and ends up executing JS code without realizing that is what was going to happen. Roughly said, I don't care if the Shaarli admin does stupid things (each their own responsibilities, as we've said here a couple of times already), but I want to somehow protect the passer-by visiting a Shaarli page. Further comments indeed welcome.

**Comment by nodiscc** [comment]
:point_up: [Discussing this on gitter](https://gitter.im/shaarli/Shaarli?at=54ee407ead31aa9748776b17) :)

**Comment by nodiscc** [comment]
I've just re-read a [bug report on the RequestPolicyContinued](https://github.com/RequestPolicyContinued/requestpolicy/issues/447) bug tracker. There are _a lot_ of existing URI schemes aside from `http: https: ftp: magnet:` (the linked bug report references `feed: mailto: magnet: mediasource: about: jar: gopher: UT2004: spotify: chrome-extension: floatnotes: greasemonkey: bank-id:` and mooore) and I think we should allow users to bookmark them.

@e2jk has concerns about the security of this, and the workaround (popup) is IMHO not so good. 

I propose allowing users to configure extra URI schemes they want to be able to store. Eg. a config array `$GLOBALS['config']['EXTRA_ALLOWED_URIS'] = array('javascript:', 'mailto:', mediasource');` and loop over this for `if (!startsWith($url,$allowed_uri)`.

Would that that be ok?

**Comment by nodiscc** [comment]
Tested and working. Merging as no further arguments have been provided, and there is no security risk for Shaarli users here. Please open another issue if you think you've found a malicious use for this, or if it's broekn in some way. Check https://nodiscc.github.io/notes/#!bookmarklets.md if you need some bookmarklets to test this!

**Pull request merged**
