### PR TITLE
Make Shaarli's template W3C compliant #64

### PR DESCRIPTION
**Pull request by ArthurHoaro**
#64 

Every page should pass W3C validator. Further tests should be done, but that's a good start. Thanks to @virtualtam.

### CODE REVIEW

**Comment by nodiscc** [comment]
Hi @ArthurHoaro thanks for working on this. I'll be glad to merge your changes if each commit message details what points from #64 are fixed in it. You are not forced to fix the W3C compliance in _ONE_ PR. For example a PR with only this would be welcome;

```
W3C compliance: fix duplicate IDs
  * #paging_older, #paging_newer become classes as the paging is displayed twice (top, bottom) in the linklist
  * work on https://github.com/shaarli/Shaarli/issues/64
```
 Let me know if you need help with git commands needed to do this (you may need to split your commits using  `git rebase -i`)

**Comment by ArthurHoaro** [comment]
Let me know if that's good enough.

**Comment by nodiscc** [comment]
Everything ok, thanks for the patch!

There are some missing explanations in the commit message (see above), can you add them? (and there is a duplicate line in the message). Just a `git commit --amend` on the w3c branch really. Otherwise I could do it when I get some time.

```
git remote add arthurhoaro https://github.com/ArthurHoaro/Shaarli/
git remote update; git checkout w3c; git commit --amend; #edit message here
git checkout master; git merge w3c
```

**Comment by ArthurHoaro** [comment]
> * Edit: I get it now. please add Fix missing alt attributes for img elements to the commit message.
> * Please add to the commit message: tpl/daily: Use HTML entities instead of char escape codes
> * Was the closing </span> missing?
>   If so please add tpl/export: fix missing </span> closing tag to the commit message
> * Please add Remove obsolete language attribute on <script> elements to the commit message

Done. :)

**Comment by nodiscc** [comment]
merci bien

**Comment by nodiscc** [comment]
Continuing on https://github.com/shaarli/Shaarli/issues/64

**Pull request merged**
