### PR TITLE
Firefox Share: Use selected text as description

### PR DESCRIPTION
**Pull request by nodiscc**
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API/Share

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Were you able to make it work?

**Comment by nodiscc** [comment]
The selected text doesn't get copied to the description field. If someone wants to look into that. Else we can just remove description prefilling.

**Comment by alexisju** [comment]
If selected text can't be copied, i personaly prefer to keep the current behavior. 

When website / article are well configure / wrote it is just nice to have the description prefilled.

**Comment by ArthurHoaro** [comment]
I've reported the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1265152

I'd say we let this PR pending until the issue has been addressed (hopefully it won't take 10 years :)).

**Comment by nodiscc** [comment]
I noticed it _does_ work when 

 * Selecting the text to use as description
 * Right-click the selected text -> `Share selection`

In fact the selected text is only ignored by the Firefox Share _button_.

What do you think about this change?

**Comment by nodiscc** [comment]
Closing. I have disabled Firefox Social API in `about:config` and plan to use the bookmarklet in the future. There are so few sites that support it that enabling this feature + extra toolbar button for just 1 service didn't make much sense. Lost interest in working on this change, feel free to reopen if you want to work on it.

**Comment by ArthurHoaro** [comment]
> There are so few sites that support it

I thought it was working everywhere?

**Comment by nodiscc** [comment]
@ArthurHoaro I meant very few sharing providers. Shaarli was the only provider enabled in FF Share.

**Comment by alexisju** [comment]
Maybe it is because you don't use main social networks. For my job i use the Firefox Social Api sharer with Facebook, Tumblr, Twitter, Diaspora, LinkedIn and, of course, Shaarli. I really prefer to have this button that several bookmarklets.

**Comment by nodiscc** [comment]
Cool. I was starting to wonder whether people actually used FF Share (with several providers). I myself have several [bookmarklets](https://github.com/nodiscc/scriptz/blob/master/SHEETS/BOOKMARKLETS.md) stashed in a bookmarks folder (with blank Name) in my bookmarks toolbar. Most of them have no Firefox Share implementation, so Shaarli was my only use for the share button.

I liked the fact that there's no popup window/page change when using it. Also, no CSP problems.

Sooo I initially thought this was quick enough to fix in my available time, but it actually looks complex. Please commit possible improvements against the `ff-share-description` branch. Or let's wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1265152 to be answered (according to https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API/Share my fix _should_ work, right? - Ping @mixedpuppy, if you could share some insight, I saw you were working on the Social API)

As a reminder, this was brought up at https://gitter.im/shaarli/Shaarli:

>@nodiscc
>https://github.com/shaarli/Shaarli/blob/master/tpl/tools.html#L82 : should the Firefox Share prefilled description be removed? Using the bookmarklet, description is prefilled with the current mouse selection, not the page's <meta name="Description" tag. I think it should also be the case here. (more often than not the prefilled description is not relevant, for me)

>@ArthurHoaro
>Well... I agree that the description tag is generally irrelevant. We could probably remove it.

**Comment by mixedpuppy** [comment]
I've commented on the bugzilla bug.  Essentially text selection sharing only works via the context menu.  Share is used by people, but generally the top social sites are most activated.  You can see the larger list at activations.mozilla.org

**Comment by ArthurHoaro** [comment]
Thanks for answer @mixedpuppy. I'm in favor of merging this. I never noticed the share entry in the contextual menu, but I don't mind using it instead of the button.

**Comment by nodiscc** [comment]
@ArthurHoaro @virtualtam Ok to merge?

**Comment by ArthurHoaro** [comment]
yup

**Comment by nodiscc** [comment]
Merged c3599302aaf9f7bf25601f21beff1946aa1737d1

**Pull request closed without merging**
