### PR TITLE
Created a Google Analytics plugin

### PR DESCRIPTION
**Pull request by ericjuden**

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Hi @ericjuden. Thanks for your contribution.

I'm not really enthusiastic about shipping a GA plugin by default. Shaarli's a free self-hosted tool, and as such we tend to focus on FOSS solutions for plugins instead of commercial products, as we did with Isso, Wallabag or Piwik.

If this doesn't get merged, you can host it on a separate repo and be listed as a [3rd party plugin](https://github.com/shaarli/Shaarli/wiki/Community-%26-Related-software#third-party-plugins).

ping @nodiscc and @virtualtam

**Comment by nicolasdanelon** [comment]
what about a rebrand? maybe if the plugin is renamed we can add self hosted analytics like piwik or something... maybe with a rename and a change of texts the plugin can be used

**Comment by nodiscc** [comment]
I agree with @ArthurHoaro's review, I wouldn't add a plugin that relies on a commercial/closed-source 3rd party service as part of the default install, especially since we already have a Piwik Analytics plugin. 

This GA plugin can be listed in https://github.com/shaarli/Shaarli/wiki/Community-%26-Related-software#third-party-plugins however, provided it has it's own repo and appropriate installation instructions.

**Comment by ericjuden** [comment]
Thanks everyone. I totally understand. I actually started with making a repository for the plugin. How do I go about getting it on the 3rd party plugins page? 

https://github.com/ericjuden/Shaarli-Google-Analytics-Plugin

**Comment by virtualtam** [comment]
Hi @ericjuden ! The wiki pages are open for editing to any logged in GitHub user ;-)

**Comment by ericjuden** [comment]
Thanks @virtualtam. I was on my mobile earlier. I'll edit the page

**Pull request closed without merging**
