### PR TITLE
fix version number

### PR DESCRIPTION
**Pull request by agentcobra**
The version number is incorrect, this is a fix to indicate the latest version

### CODE REVIEW

**Comment by nodiscc** [comment]
I think this branch (`latest`) is an old/unused branch, it should be deleted completely.

**Comment by nodiscc** [comment]
This is definitely an old branch with no purpose anymore. i will delete it.

image

@agentcobra maybe if you explained the actual problem you're having, in a new issue, we could find a proper solution?

**Comment by agentcobra** [comment]
see https://github.com/shaarli/Shaarli/blob/master/application/front/controller/admin/ServerController.php#L30

**Comment by nodiscc** [comment]
Ok! I reported the actual bug to https://github.com/shaarli/Shaarli/issues/1961, I will take care of it. Thanks

**Comment by agentcobra** [comment]
is the latest branch used for docker?

**Comment by nodiscc** [comment]
> is the latest branch used for docker?

No. The `ghcr.io/shaarli/shaarli:latest` image is built from the `master` branch.

**Pull request closed without merging**
