### PR TITLE
Detect https protocol by reverse-proxy rfc7239 : X-Forwarded-Proto

### PR DESCRIPTION
**Pull request by fanch317**
Fix bad URL for thumbnails images in page index.

### CODE REVIEW

**Comment by virtualtam** [comment]
Hello @fanch317!

Looking at the following RFCs:
- [7239](http://www.ietf.org/rfc/rfc7239.txt) - Forwarded HTTP Extension
- [6648](http://www.ietf.org/rfc/rfc6648.txt) - Deprecating the "X-" Prefix and Similar Constructs in Application Protocols

it seems that `X-Forwarded-Proto` _should be_ deprecated by now; could you add some precisions on which HTTP servers support / use it?

Potentially related: #319 - Shaarli via proxy: cannot login
Added to #324 - Code refactoring memo

**Comment by fanch317** [comment]
Hello virtualtam,
Thanks for this details.

Indeed, the RFC 6648 indicate do not create tags but suggest read existings tags "X-" for compatibity.
Problem : X-Forwarded-Proto has been created after this RFC and not other tags exists.

My config is:
Browser --> reverse nginx (**https**://shaarli.domain) --> webhost (**http**://shaarli.domain)
For me, i use a reverse proxy nginx with ssl before to access shaarli (this webhosting don't have any SSL sertificate). I have try to use a existing tag in RFC.

So i can use another tag for more respect of RFC but this tag hasn't been replaced. (tag X-Forwarded-For too)

**Comment by virtualtam** [comment]
Thanks for the use case explanation :)

I'm OK for merging, could you:
- [rebase](http://www.git-scm.com/book/en/v2/Git-Branching-Rebasing) the commit upon `master`
- [amend](http://www.git-scm.com/book/en/v2/Git-Basics-Undoing-Things) the commit message to
```
HTTPS detection: add support for `X-Forwarded-Proto`

See:
 - RFC 7239 - Forwarded HTTP Extension
   http://www.ietf.org/rfc/rfc7239.txt
 - RFC 6238 - Deprecating the "X-" Prefix and Similar Constructs in Application Protocols
   http://www.ietf.org/rfc/rfc6648.txt
 - StackOverflow - Custom HTTP headers: naming conventions
   http://stackoverflow.com/a/3561399
```

Unit tests and code cleanup will be handled in #346

**Comment by virtualtam** [comment]
Cherry-picked and merged in #346

**Pull request closed without merging**
