### PR TITLE
New default template

### LINKED ISSUE #266: Page template & CSS rewrite
## Goals
- provide W3C-compliant HTML5 & CSS code
- improve metadata, add semantics (see #258)
- rewrite page templates using a modern, lightweight engine
- hook template rendering with an HTTP router (see #655)
- rewrite the main stylesheet: simple, responsive and flexible (easy to extend/override)
- use an icon font subset instead of images
- give the community fork its own identity (see #203)
### Template engines
- ~~[RainTPL](https://github.com/rainphp/raintpl), [RainTPL3](https://github.com/rainphp/raintpl3)~~ the official website is down -domain suspended, and the repositories don't seem actively maintained...
- ~~[Dwoo](http://dwoo.org/)~~ no built-in integration in Slim/Silex
- [Smarty](http://www.smarty.net/)
- [Twig](http://twig.sensiolabs.org/)
### Responsive stylesheets
- [Bootstrap](http://getbootstrap.com/), and [Bootswatch](http://bootswatch.com/) for custom theme design
- [Ink](http://ink.sapo.pt/)
- [Smart Grid](https://dryan.github.io/css-smart-grid/)
### Icon fonts
- [Font Awesome](http://fontawesome.io/)
- [Glyphicons](http://glyphicons.com/)
- [Ionicons](http://ionicons.com/)
- [Glyphsearch](http://glyphsearch.com/) (font search engine)
## Resources
- [Dive into HTML5](http://fortuito.us/diveintohtml5/)
- [HTML Dog](http://www.htmldog.com/)
- [Responsive design guidelines](http://responsivedesign.is/guidelines)
- [CSS tricks](https://css-tricks.com/)
## Notes
- this started as a discussion brought by @nodiscc on [Gitter](https://gitter.im/shaarli/Shaarli)
- everyone is welcome to provide feedback or suggest other frameworks, libraries and resources, I'll keep this issue updated :)

### PR DESCRIPTION
**Pull request by ArthurHoaro**
After almost a year, here is the new default template! It replaces the current default template.

It uses PureCSS and FontAwesome. It keeps the same layout but a bit more modern, with a few additional front end features (search from everywhere, login everywhere, etc).

The current template is still available (and will have to be maintained, at least to keep it working) under `vintage` folder and name.

See #266 for more info.

Fixes #266 #589 #585 #544 #439 

EDIT: it's a lot of LOC, but note that a lot of it comes from uncompressed JS/CSS libs which aren't used.

Edit bis: I've forgot to mention it, but the huge improvement is that this template is responsive.

### CODE REVIEW

**Comment by nodiscc** [comment]
Thank you for this huge work 👏 

I've started reading the commits and

> it's a lot of LOC, but note that a lot of it comes from uncompressed JS/CSS libs which aren't used.
> 45 changed files in  	7262e18

Is it possible/recommended to fetch 3rd-party eot,css,js... files during the build process? (as opposed to storing them in the git repository)

**Comment by ArthurHoaro** [comment]
Yes. We could use bower (dependency manager, kind of like composer, for front end libs) and include these in our release archives.

**Comment by virtualtam** [comment]
#755 opened to discuss Bower usage :)

**Comment by ArthurHoaro** [comment]
Rebased and additional bunch of changes: 

  * Add API settings in `configure.html`
  * Fix textarea autoresize
  * Load user.css from data folder
  * Move fold/expand all button to the right and fix an issue with already folded items
  * Reset datetime display to international datetime
  * Temporarily remove JS login panel (need improvement and integration with the plugin system)
  * Body background is slightly lighter
  * Fix an issue where thumbnails were hidden by description
  * Fix an issue where private orange bar wasn't displayed with thumbnails
  * Remove the gradient bar under titles
  * Fix empty bookmarklet name in Firefox

-----

This PR is a bit blocking further developments and I understand that reviewing hundreds of line of templates and CSS is neither easily doable nor fun. I suggest that we merge this PR, and work toward improving the new theme for v0.9.0, which isn't going to be release so soon since the API is still being written.

**Comment by nodiscc** [comment]
>  I suggest that we merge this PR, and work toward improving the new theme for v0.9.0,

:+1:

**Comment by virtualtam** [comment]
Might be a good idea to set the `vintage` theme as the default one while we work on the new one :)

https://github.com/shaarli/Shaarli/issues/755#issuecomment-282495085 regarding frontend dependency management

**Comment by ArthurHoaro** [comment]
@virtualtam Good idea.

**Comment by dajare** [comment]
I've just started using Shaarli in the past week -- I love it!

I have to say that I was expecting/hoping that [this theme][1] is the one I would see "out of the box", and was disappointed that it wasn't. The "Material" theme is working well for me now, but if the proposed "default" theme had been there to start with, I might not even have felt the need to go looking for others! (...but would have done eventually: that's what users do!)

I hope this new theme will "ship" with Shaarli *soon*. :)

[1]: http://workspace.hoa.ro/shaarli/

**Comment by ArthurHoaro** [comment]
Hi, the new theme will be shipped with Shaarli with the release of `v0.9.0`, *soon*.

**Pull request merged**
