### PR TITLE
Sticky footer

### PR DESCRIPTION
**Pull request by nicolasdanelon**
This pull request adds sticky footer to all pages in Shaarli.

### CODE REVIEW

**Comment by nodiscc** [comment]
Can you explain what it does? It just adds a blank div

**Comment by nicolasdanelon** [comment]
the footer is always in the bottom of the page. I've test every page, works fine. Plase try to clone my branch and lunch a

**php -S localhost:90001 -t /path/to/index/file**

and you‘ll see the code in action :)

**Comment by nicolasdanelon** [comment]
fast [example](http://getbootstrap.com/examples/sticky-footer/) here 
same logic..

**Comment by nodiscc** [comment]
Sorry I don't think this is really useful. Shaarli's footer doesn't really contain useful information.
I'll close this tomorrow if no one else disagrees.

**Comment by nicolasdanelon** [comment]
the idea behind this PR is have a more neat and clean interface. One more day is too shot time :/

**Comment by nodiscc** [comment]
The floating footer hides info behind it and provides no valuable info itself. Leaving this open until Sunday 12.

**Comment by nicolasdanelon** [comment]
Hides info behind? where? please tell me, coz I use this code everywhere and I never see any bug.

screenshot from 2015-04-10 23-54-29

Every good web development (like [Google home page](https://encrypted.google.com/), [Google sign in](https://accounts.google.com/Login) or [A list apart](alistapart.com/contact)) use sticky footer. Bootstrap gots and example for this and other css frameworks too.. this makes a better interface

**Comment by nodiscc** [comment]
Indeed it doesn't hide content (must have mixed up my branches). However I'm still not sure we should merge this: It adds a padding problem:

before:
before

after:
after

 and sticks the footer to the page bottom which is not an obvious benefit (lots of blank space):

before:
full-before

after:
full-after

I'll leave this open for another week in case someone wants to make a case for it

**Comment by pikzen** [comment]
@nicolasdanelon 's last link is broken, it should be http://alistapart.com/contact. (Which, ironically enough has no sticky footer and is pretty broken for me.). I don't believe they are particularly good examples though, as Google has some real info to display in here, as opposed to Shaarli (because let's be honest, visitors rarely give a crap about "what software is this running?"). There are also examples with non sticky footers, like Facebook (even though they decided to implement autoloading) or Reddit. I rarely look at footers though, so I don't have much of an opinion on this PR.

The whitespace issue is mostly due to Shaarli's default theme being bad in regard to space usage. While links are displayed under the menubar, everything else is basically crammed in the menubar.
However, this issue is only* present in admin facing links (i.e. add link, tools, login, etc.) which are pages 1) rarely accessed 2) viewed only by one person.

* : We can assume that any Shaarli with 10+ links will already push the footer down the page.

**Comment by nodiscc** [comment]
Closing. If you want to propose a more radical rewrite for the default template/css, please go ahead and open a new issue with a proposition.

**Pull request closed without merging**
