### PR TITLE
Fixes #356 -  adding a link should return added link's hash

### LINKED ISSUE #356: adding a link should return added link's hash
feature existed from the early days and was IMO accidentally removed with 775803a0.

As the link's hash is the confirmation that the link really was added it's more than useful not only for #71 and testing in general, but also for #16, #113, #342, #130. Related to PR #354 also.

### PR DESCRIPTION
**Pull request by ArthurHoaro**
Not related, but already discussed in #354:
* allow redirection on relative urls in generateLocation

cf #357

### CODE REVIEW

**Comment by ArthurHoaro** [comment]
Ping @mro. Can you confirm it fixes your issue?

**Comment by mro** [comment]
Thanks you @ArthurHoaro,

yes, it fixes PR #354 - see https://travis-ci.org/mro/Shaarli/builds/89303349 - so it looks promising. Will install it on a server and test manually within 24h.

**Comment by mro** [comment]
...also fixes https://travis-ci.org/mro/Shaarli-API-test/builds/89308107

So as far as I'm concerned, I'd love to see this in `master`. (Will test manually also as promised however).

**Comment by mro** [comment]
confirmed fixed, thanks a lot. When do you think will we see this in `master`?

**Comment by mro** [comment]
stop, am confused, have to check once more.

**Comment by mro** [comment]
confirmed good.

**Comment by ArthurHoaro** [comment]
Glad to hear that! I'll probably wait till this weekend merge it, just in case.

**Comment by mro** [comment]
(OT, travis currently seems to have issues with it's build system - builds don't just fail but crash in early stages: https://travis-ci.org/mro/Shaarli-API-test/builds/89544991)

**Comment by mro** [comment]
obsoletes #354

**Pull request merged**
