### PR TITLE
picwall: link directly to the target URL (not the permalink)

### PR DESCRIPTION
**Pull request by nodiscc**

### CODE REVIEW

**Comment by virtualtam** [comment]
The instantiation of `$link['permalink']` should also be removed from `index.php`, l. 1274:

```php
1266        // Get only links which have a thumbnail.
1267        foreach($links as $link)
1268        {
1269            $permalink='?'.htmlspecialchars(smallhash($link['linkdate']),ENT_QUOTES);
1270            $thumb=lazyThumbnail($link['url'],$permalink);
1271            if ($thumb!='') // Only output links which have a thumbnail.
1272            {
1273                $link['thumbnail']=$thumb; // Thumbnail HTML code.
1274                $link['permalink']=$permalink; // Hullo! Could you please remove me? ;-)
1275                $linksToDisplay[]=$link; // Add to array.
1276            }
1277        }
```

**Comment by nodiscc** [comment]
@virtualtam well spotted, I removed it. By the way this could be a test for https://github.com/shaarli/Shaarli/issues/71 (unused variables)

**Comment by nodiscc** [comment]
Merging on Sunday 15, March 2015. Please comment if you think we should not merge.

**Comment by virtualtam** [comment]
The difficulty with unused variables is that they are:
* declared / instantiated in `index.php`,
* used in templates, which are called by their URL + POST/GET/SESSION variables.

Thus, static code checkers are not able to connect variable declaration to variable usage... So we need to be careful with templates :)

**Comment by ArthurHoaro** [comment]
I work a lot with Sonar in Java, and this case wouldn't raise any alert: `$permalink` is used with `$link` which is itself used for `$linksToDisplay`. Any variable sent to RainTPL will be used, so it's probably a safe rule to add.

**Pull request merged**
